# Generated by Django 5.2.16 on 2026-08-06 12:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0007_post_ai_analysis'),
        ('profiles', '0005_profile_creator_balance_profile_creator_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('walk', 'Walking'), ('run', 'Running'), ('hike', 'Hiking'), ('cycle', 'Cycling')], default='run', max_length=10)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('gps', 'GPS'), ('import', 'Imported')], default='gps', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('distance_meters', models.FloatField(default=0.0)),
                ('avg_pace', models.FloatField(blank=True, help_text='Seconds per kilometre', null=True)),
                ('avg_speed_kmh', models.FloatField(blank=True, null=True)),
                ('calories_burned', models.FloatField(blank=True, null=True)),
                ('steps', models.IntegerField(blank=True, null=True)),
                ('elevation_gain_m', models.FloatField(blank=True, null=True)),
                ('route', models.JSONField(blank=True, default=list, help_text='List of [lat, lng, timestamp] trackpoints')),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='profiles.profile')),
            ],
            options={
                'db_table': 'analytics_activity_record',
                'ordering': ['-started_at', '-created_at'],
                'indexes': [models.Index(fields=['user', '-started_at'], name='analytics_a_user_id_def87d_idx'), models.Index(fields=['user', 'activity_type'], name='analytics_a_user_id_3bd866_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(default='all', max_length=10)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('data', models.JSONField(default=dict)),
                ('image_url', models.URLField(blank=True)),
                ('feed_post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_report', to='feed.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_reports', to='profiles.profile')),
            ],
            options={
                'db_table': 'analytics_report',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='analytics_r_user_id_5f8abb_idx')],
            },
        ),
        migrations.CreateModel(
            name='BodyMetric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight_kg', models.FloatField()),
                ('body_fat_pct', models.FloatField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('measured_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_metrics', to='profiles.profile')),
            ],
            options={
                'db_table': 'analytics_body_metric',
                'ordering': ['-measured_at', '-created_at'],
                'indexes': [models.Index(fields=['user', '-measured_at'], name='analytics_b_user_id_c87781_idx')],
            },
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('drink', 'Drink'), ('other', 'Other')], default='meal', max_length=20)),
                ('food_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('protein_g', models.FloatField(blank=True, null=True)),
                ('carbs_g', models.FloatField(blank=True, null=True)),
                ('fat_g', models.FloatField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('photo', 'Photo recognition'), ('meal_plan', 'Meal plan')], default='manual', max_length=20)),
                ('logged_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to='profiles.profile')),
            ],
            options={
                'db_table': 'analytics_meal_log',
                'ordering': ['-logged_at', '-created_at'],
                'indexes': [models.Index(fields=['user', '-logged_at'], name='analytics_m_user_id_d6b8a4_idx'), models.Index(fields=['user', 'meal_type'], name='analytics_m_user_id_f9225d_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workout_type', models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('hiit', 'HIIT'), ('yoga', 'Yoga'), ('mobility', 'Mobility'), ('sport', 'Sport'), ('other', 'Other')], default='strength', max_length=20)),
                ('exercise', models.CharField(blank=True, max_length=120)),
                ('sets', models.IntegerField(blank=True, null=True)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('calories_burned', models.FloatField(blank=True, null=True)),
                ('distance_meters', models.FloatField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to='profiles.profile')),
            ],
            options={
                'db_table': 'analytics_workout_log',
                'ordering': ['-performed_at', '-created_at'],
                'indexes': [models.Index(fields=['user', '-performed_at'], name='analytics_w_user_id_9a8bfd_idx'), models.Index(fields=['user', 'workout_type'], name='analytics_w_user_id_65a553_idx')],
            },
        ),
    ]
