# Generated by Django 5.2.16 on 2026-08-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodymetric',
            name='scale_photo_url',
            field=models.URLField(blank=True, help_text='Photo of the digital scale display showing the weight'),
        ),
    ]
