# Generated by Django 5.2.17 on 2026-08-25 18:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_bodymetric_scale_photo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(default='trophy', max_length=30)),
                ('metric', models.CharField(choices=[('workouts_logged', 'Workouts logged'), ('meals_logged', 'Meals logged'), ('activities_distance_km', 'GPS activity distance (km)'), ('posts_shared', 'Posts shared'), ('streak_days', 'Current streak (days)'), ('buddies_made', 'Confirmed buddies')], max_length=30)),
                ('threshold', models.PositiveIntegerField()),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=12)),
            ],
            options={
                'db_table': 'analytics_achievement',
                'ordering': ['period', 'threshold'],
                'unique_together': {('metric', 'threshold', 'period')},
            },
        ),
    ]
