# Generated by Django 5.2.17 on 2026-09-21 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_analyticsevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MealLog',
        ),
    ]
