# Generated by Django 5.2.17 on 2026-10-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_delete_meallog'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='category',
            field=models.CharField(blank=True, choices=[('upper', 'Upper'), ('lower', 'Lower'), ('legs', 'Legs'), ('push', 'Push'), ('pull', 'Pull'), ('core', 'Core'), ('arms', 'Arms'), ('full', 'Full')], default='', max_length=20),
        ),
    ]
