# Generated by Django 5.2.17 on 2026-10-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_workoutlog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='category',
            field=models.CharField(blank=True, choices=[('ankles', 'Ankles'), ('arms', 'Arms'), ('balance', 'Balance'), ('basketball', 'Basketball'), ('cardio', 'Cardio'), ('core', 'Core'), ('cricket', 'Cricket'), ('flexibility', 'Flexibility'), ('football', 'Football'), ('full', 'Full'), ('hips', 'Hips'), ('legs', 'Legs'), ('lower', 'Lower'), ('mindfulness', 'Mindfulness'), ('mobility', 'Mobility'), ('netball', 'Netball'), ('other', 'Other'), ('posture', 'Posture'), ('pull', 'Pull'), ('push', 'Push'), ('rugby', 'Rugby'), ('shoulders', 'Shoulders'), ('spine', 'Spine'), ('strength', 'Strength'), ('tennis', 'Tennis'), ('upper', 'Upper'), ('volleyball', 'Volleyball')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='workout_type',
            field=models.CharField(choices=[('strength', 'Strength'), ('hiit', 'HIIT'), ('cardio', 'Cardio'), ('running', 'Running'), ('walking', 'Walking'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('climbing', 'Climbing'), ('rowing', 'Rowing'), ('dance', 'Dance'), ('yoga', 'Yoga'), ('pilates', 'Pilates'), ('mobility', 'Mobility'), ('sport', 'Sport'), ('boxing', 'Boxing'), ('martial_arts', 'Martial Arts'), ('other', 'Other')], default='strength', max_length=20),
        ),
    ]
