# Generated by Django 5.2.15 on 2026-06-23 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gym",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("handle", models.CharField(max_length=60, unique=True)),
                ("description", models.TextField(blank=True, max_length=500)),
                ("logo_url", models.URLField(blank=True)),
                ("cover_url", models.URLField(blank=True)),
                ("category", models.CharField(max_length=50)),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("secret", "Secret"),
                        ],
                        default="public",
                        max_length=8,
                    ),
                ),
                (
                    "subscription_type",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("members_free", "Free (Members Only)"),
                            ("paid", "Paid"),
                            ("tiered", "Tiered"),
                        ],
                        default="free",
                        max_length=15,
                    ),
                ),
                ("monthly_fee_artifacts", models.JSONField(blank=True, null=True)),
                ("join_fee_artifacts", models.JSONField(blank=True, null=True)),
                ("wallet_balance", models.JSONField(default=dict)),
                ("is_verified", models.BooleanField(default=False)),
                ("rules", models.JSONField(default=list)),
                ("tags", models.JSONField(default=list)),
                ("member_count", models.IntegerField(default=0)),
                ("location_city", models.CharField(blank=True, max_length=100)),
                ("location_country", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "db_table": "gyms_gym",
                "indexes": [
                    models.Index(fields=["name"], name="gyms_gym_name_ee4a7a_idx"),
                    models.Index(fields=["handle"], name="gyms_gym_handle_02e3a2_idx"),
                    models.Index(
                        fields=["category"], name="gyms_gym_categor_39a8f7_idx"
                    ),
                    models.Index(
                        fields=["access_type"], name="gyms_gym_access__e922f5_idx"
                    ),
                    models.Index(
                        fields=["location_city", "location_country"],
                        name="gyms_gym_locatio_72e0d6_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GymMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("co_owner", "Co-Owner"),
                            ("trainer", "Trainer"),
                            ("moderator", "Moderator"),
                            ("member", "Member"),
                            ("guest", "Guest"),
                        ],
                        default="member",
                        max_length=15,
                    ),
                ),
                ("subscription_active", models.BooleanField(default=True)),
                (
                    "subscription_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="gyms.gym",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gym_memberships",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "gyms_gym_membership",
                "indexes": [
                    models.Index(
                        fields=["member", "subscription_active"],
                        name="gyms_gym_me_member__dbd15e_idx",
                    )
                ],
                "unique_together": {("gym", "member")},
            },
        ),
    ]
