# Generated by Django 5.2.15 on 2026-07-01 16:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gyms", "0003_gymcategory_gym_categories_gymcategorypricing_and_more"),
        ("profiles", "0002_profile_saved_payment_methods"),
    ]

    operations = [
        migrations.AddField(
            model_name="gym",
            name="is_donations_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gym",
            name="is_reviews_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="GymDonation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("message", models.TextField(blank=True, max_length=500)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gym_donations",
                        to="profiles.profile",
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to="gyms.gym",
                    ),
                ),
            ],
            options={
                "db_table": "gyms_donation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GymSchedulePost",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=150)),
                ("content", models.TextField(max_length=2000)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gym_schedule_posts",
                        to="profiles.profile",
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_posts",
                        to="gyms.gym",
                    ),
                ),
            ],
            options={
                "db_table": "gyms_schedule_post",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GymReview",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                ("comment", models.TextField(blank=True, max_length=1000)),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="gyms.gym",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gym_reviews",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "gyms_review",
                "ordering": ["-created_at"],
                "unique_together": {("gym", "reviewer")},
            },
        ),
    ]
