# Generated by Django 5.2.15 on 2026-07-01 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gyms", "0004_gym_is_donations_enabled_gym_is_reviews_enabled_and_more"),
        ("profiles", "0002_profile_saved_payment_methods"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gymschedulepost",
            name="scheduled_for",
        ),
        migrations.AddField(
            model_name="gymreview",
            name="replied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gymreview",
            name="replied_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gym_review_replies",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="gymreview",
            name="reply_text",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="gymschedulepost",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("yoga", "Yoga Class"),
                    ("hiit", "HIIT Session"),
                    ("strength", "Strength & Conditioning"),
                    ("cardio", "Cardio Class"),
                    ("live_stream", "Live Stream"),
                    ("workshop", "Workshop / Seminar"),
                    ("event", "Special Event"),
                    ("session", "Session"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="gymschedulepost",
            name="custom_activity_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="gymschedulepost",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gymschedulepost",
            name="location_mode",
            field=models.CharField(
                choices=[
                    ("in_house", "In House"),
                    ("online", "Online"),
                    ("hybrid", "Hybrid"),
                ],
                default="in_house",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="gymschedulepost",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gymschedulepost",
            name="content",
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
