# Generated by Django 5.2.15 on 2026-07-04 21:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gyms", "0005_remove_gymschedulepost_scheduled_for_and_more"),
        ("lives", "0006_liveattendee"),
        ("profiles", "0002_profile_saved_payment_methods"),
    ]

    operations = [
        migrations.AddField(
            model_name="gymschedulepost",
            name="linked_live",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedule_slots",
                to="lives.buddylive",
            ),
        ),
        migrations.AddField(
            model_name="gymschedulepost",
            name="max_slots",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gymschedulepost",
            name="recurrence",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="gymschedulepost",
            name="recurrence_days",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="gymschedulepost",
            name="recurrence_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gymschedulepost",
            name="slots_taken",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gymschedulepost",
            name="timezone",
            field=models.CharField(default="UTC", max_length=60),
        ),
        migrations.CreateModel(
            name="ScheduleSlotEnrollment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("none", "One-time"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("recurrence_end_date", models.DateField(blank=True, null=True)),
                ("reminder_minutes", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slot_enrollments",
                        to="profiles.profile",
                    ),
                ),
                (
                    "schedule_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="gyms.gymschedulepost",
                    ),
                ),
            ],
            options={
                "db_table": "gyms_slot_enrollment",
                "ordering": ["-created_at"],
                "unique_together": {("schedule_post", "member")},
            },
        ),
    ]
