# Generated by Django 5.2.15 on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gyms", "0007_gymmembershipexception"),
    ]

    operations = [
        migrations.AddField(
            model_name="gym",
            name="content_rating",
            field=models.CharField(
                choices=[("general", "General (all ages)"), ("mature", "Mature (18+ / 16+)")],
                default="general",
                max_length=10,
            ),
        ),
    ]
