# Generated by Django 5.2.17 on 2026-09-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0009_partner_readiness'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='venuelocation',
            index=models.Index(fields=['is_active', 'latitude', 'longitude'], name='gyms_venue_geo_idx'),
        ),
    ]
