import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:media_kit/media_kit.dart';
import 'package:media_kit_video/media_kit_video.dart';

import '../../../core/analytics/analytics_service.dart';
import '../../../core/theme/app_theme.dart';
import '../../../core/utils/constants.dart';
import '../../../shared/widgets/toast.dart';
import '../providers/sounds_provider.dart';
import 'post_composer_screen.dart';

/// Everything the composer needs to remember from the studio flow.
class VideoStudioResult {
  final int trimStartMs;
  final int trimEndMs;
  final String? soundId;
  final double? soundVolume; // 0..1, null when original audio
  final String visibility;
  final bool commentsEnabled;

  const VideoStudioResult({
    required this.trimStartMs,
    required this.trimEndMs,
    this.soundId,
    this.soundVolume,
    required this.visibility,
    required this.commentsEnabled,
  });
}

/// Studio the composer routes to after a video is picked. Steps:
/// trim → sound → audience → cover/publish. The cover is generated by the
/// upload pipeline (Cloudinary eager) and only surfaced here once known.
class VideoStudioScreen extends ConsumerStatefulWidget {
  final ComposerMedia video;
  final String initialVisibility;

  const VideoStudioScreen({
    super.key,
    required this.video,
    this.initialVisibility = 'public',
  });

  @override
  ConsumerState<VideoStudioScreen> createState() => _VideoStudioScreenState();
}

class _VideoStudioScreenState extends ConsumerState<VideoStudioScreen> {
  Player? _player;
  VideoController? _controller;
  StreamSubscription<Duration>? _positionSub;

  int _durationMs = 0;
  int _trimStartMs = 0;
  int _trimEndMs = 0;
  bool _loopPreview = false;

  Sound? _selectedSound;
  double _soundVolume = 100;
  late String _visibility;
  bool _commentsEnabled = true;

  static const int _maxTrimMs = 180 * 1000;

  @override
  void initState() {
    super.initState();
    _visibility = widget.initialVisibility;
    AnalyticsService.instance.track(
      'create.started',
      surface: 'composer_studio',
      objectType: 'video',
      objectId: widget.video.name,
    );
    _setupPlayer();
    Future.microtask(
      () => ref.read(soundsProvider.notifier).load(ordering: 'trending'),
    );
  }

  void _setupPlayer() {
    final player = Player();
    _player = player;
    _controller = VideoController(player);
    _positionSub = player.stream.position.listen((p) {
      if (!mounted) return;
      final end = _trimEndMs;
      if (_loopPreview && end > _trimStartMs) {
        if (p.inMilliseconds >= end) {
          player.seek(Duration(milliseconds: _trimStartMs));
        }
      }
    });
    player.stream.duration.listen((d) {
      if (!mounted || d.inMilliseconds <= 0) return;
      setState(() {
        _durationMs = d.inMilliseconds;
        final end = _durationMs < _maxTrimMs ? _durationMs : _maxTrimMs;
        if (_trimEndMs == 0 || _trimEndMs > end) _trimEndMs = end;
      });
    });
    player.open(Media(widget.video.path), play: false);
  }

  @override
  void dispose() {
    _positionSub?.cancel();
    _player?.dispose();
    super.dispose();
  }

  Future<void> _openTrimSheet() async {
    if (_durationMs <= 0) {
      showToast(context, 'Video is still loading — try again in a moment');
      return;
    }
    final result = await showModalBottomSheet<({int start, int end})>(
      context: context,
      backgroundColor: BuddyColors.surface,
      isScrollControlled: true,
      builder: (_) => _TrimSheet(
        durationMs: _durationMs,
        initialStartMs: _trimStartMs,
        initialEndMs: _trimEndMs,
        maxTrimMs: _maxTrimMs,
      ),
    );
    if (result == null) return;
    if (!mounted) return;
    setState(() {
      _trimStartMs = result.start;
      _trimEndMs = result.end;
    });
    AnalyticsService.instance.track(
      'create.trim_set',
      surface: 'composer_studio',
      objectType: 'video',
      objectId: widget.video.name,
      properties: {
        'trim_start_ms': _trimStartMs,
        'trim_end_ms': _trimEndMs,
      },
    );
    showToast(context, 'Trim saved', type: ToastType.success);
  }

  Future<void> _openSoundSheet() async {
    final result = await showModalBottomSheet<({Sound? sound, double volume})>(
      context: context,
      backgroundColor: BuddyColors.surface,
      isScrollControlled: true,
      builder: (_) => _SoundSheet(initialSelectedSoundId: _selectedSound?.id),
    );
    if (result == null) return;
    if (!mounted) return;
    setState(() {
      _selectedSound = result.sound;
      _soundVolume = result.volume;
    });
    if (result.sound != null) {
      ref.read(soundsProvider.notifier).markUsed(result.sound!.id);
      AnalyticsService.instance.track(
        'create.sound_added',
        surface: 'composer_studio',
        objectType: 'sound',
        objectId: result.sound!.id,
        properties: {
          'sound_name': result.sound!.name,
          'volume': result.volume.round(),
        },
      );
    }
  }

  Future<void> _openAudienceSheet() async {
    final result = await showModalBottomSheet<({String visibility, bool commentsEnabled})>(
      context: context,
      backgroundColor: BuddyColors.surface,
      builder: (_) => _AudienceSheet(
        initialVisibility: _visibility,
        initialCommentsEnabled: _commentsEnabled,
      ),
    );
    if (result == null) return;
    if (!mounted) return;
    setState(() {
      _visibility = result.visibility;
      _commentsEnabled = result.commentsEnabled;
    });
  }

  void _toggleLoopPreview() async {
    final player = _player;
    if (player == null) return;
    setState(() => _loopPreview = !_loopPreview);
    if (_loopPreview) {
      await player.seek(Duration(milliseconds: _trimStartMs));
      await player.play();
    } else {
      await player.pause();
    }
  }

  void _done() {
    Navigator.of(context).pop(VideoStudioResult(
      trimStartMs: _trimStartMs,
      trimEndMs: _trimEndMs,
      soundId: _selectedSound?.id,
      soundVolume: _selectedSound == null ? null : _soundVolume / 100,
      visibility: _visibility,
      commentsEnabled: _commentsEnabled,
    ));
  }

  String _fmt(int ms) {
    final total = (ms / 1000).round();
    return '${total ~/ 60}:${(total % 60).toString().padLeft(2, '0')}';
  }

  @override
  Widget build(BuildContext context) {
    final controller = _controller;
    return Scaffold(
      appBar: AppBar(title: const Text('Video Studio')),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          ClipRRect(
            borderRadius: BorderRadius.circular(16),
            child: AspectRatio(
              aspectRatio: 9 / 16,
              child: controller == null
                  ? Container(color: BuddyColors.surfaceRaised)
                  : Video(controller: controller, controls: NoVideoControls),
            ),
          ),
          if (_durationMs > 0)
            Padding(
              padding: const EdgeInsets.only(top: 8),
              child: Text(
                'Duration ${_fmt(_durationMs)}'
                '${_trimEndMs > _trimStartMs ? ' · trim ${_fmt(_trimStartMs)}–${_fmt(_trimEndMs)}' : ''}',
                style: const TextStyle(
                  color: BuddyColors.textSecondary,
                  fontSize: 12,
                ),
              ),
            ),
          const SizedBox(height: 12),
          Wrap(
            spacing: 8,
            runSpacing: 8,
            children: [
              ActionChip(
                avatar: const Icon(Icons.content_cut, size: 18, color: BuddyColors.textSecondary),
                label: Text(
                  _trimEndMs > _trimStartMs
                      ? 'Trim ${_fmt(_trimStartMs)}–${_fmt(_trimEndMs)}'
                      : 'Trim',
                  style: const TextStyle(color: BuddyColors.textPrimary, fontSize: 12),
                ),
                onPressed: _openTrimSheet,
              ),
              ActionChip(
                avatar: const Icon(Icons.music_note, size: 18, color: BuddyColors.textSecondary),
                label: Text(
                  _selectedSound?.name ?? 'Original only',
                  style: const TextStyle(color: BuddyColors.textPrimary, fontSize: 12),
                ),
                onPressed: _openSoundSheet,
              ),
              ActionChip(
                avatar: const Icon(Icons.visibility_outlined, size: 18, color: BuddyColors.textSecondary),
                label: Text(
                  'Audience: $_visibility${_commentsEnabled ? '' : ' · comments off'}',
                  style: const TextStyle(color: BuddyColors.textPrimary, fontSize: 12),
                ),
                onPressed: _openAudienceSheet,
              ),
            ],
          ),
          const SizedBox(height: 8),
          Row(
            children: [
              Expanded(
                child: OutlinedButton.icon(
                  onPressed: _toggleLoopPreview,
                  icon: Icon(_loopPreview ? Icons.pause : Icons.loop),
                  label: Text(_loopPreview ? 'Stop preview' : 'Loop preview'),
                ),
              ),
            ],
          ),
          const SizedBox(height: 12),
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: BuddyColors.surfaceRaised.withValues(alpha: 0.4),
              borderRadius: BorderRadius.circular(12),
            ),
            child: const Row(
              children: [
                Icon(Icons.image_outlined, color: BuddyColors.textSecondary, size: 20),
                SizedBox(width: 8),
                Expanded(
                  child: Text(
                    'Cover: auto-generated from your video when it uploads',
                    style: TextStyle(color: BuddyColors.textSecondary, fontSize: 12),
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 16),
          FilledButton(
            style: FilledButton.styleFrom(
              backgroundColor: BuddyColors.green,
              foregroundColor: BuddyColors.black,
            ),
            onPressed: _done,
            child: const Text('Done'),
          ),
        ],
      ),
    );
  }
}

class _TrimSheet extends StatefulWidget {
  final int durationMs;
  final int initialStartMs;
  final int initialEndMs;
  final int maxTrimMs;

  const _TrimSheet({
    required this.durationMs,
    required this.initialStartMs,
    required this.initialEndMs,
    required this.maxTrimMs,
  });

  @override
  State<_TrimSheet> createState() => _TrimSheetState();
}

class _TrimSheetState extends State<_TrimSheet> {
  late double _startMs;
  late double _endMs;

  @override
  void initState() {
    super.initState();
    _startMs = widget.initialStartMs.toDouble();
    _endMs = (widget.initialEndMs > 0
            ? widget.initialEndMs
            : widget.durationMs)
        .toDouble();
  }

  String _fmt(double ms) {
    final total = (ms / 1000).round();
    return '${total ~/ 60}:${(total % 60).toString().padLeft(2, '0')}';
  }

  void _onChanged(RangeValues values) {
    var start = values.start;
    var end = values.end;
    // Clamp the selection to ≤180s.
    if (end - start > widget.maxTrimMs) {
      if (start != _startMs) {
        start = end - widget.maxTrimMs;
      } else {
        end = start + widget.maxTrimMs;
      }
    }
    setState(() {
      _startMs = start;
      _endMs = end;
    });
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Padding(
        padding: EdgeInsets.only(
          bottom: MediaQuery.viewInsetsOf(context).bottom,
        ),
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text(
                'Trim video',
                style: TextStyle(
                  color: BuddyColors.textPrimary,
                  fontWeight: FontWeight.w600,
                  fontSize: 16,
                ),
              ),
              const SizedBox(height: 4),
              const Text(
                'Max 3:00 per clip',
                style: TextStyle(color: BuddyColors.textSecondary, fontSize: 12),
              ),
              const SizedBox(height: 12),
              RangeSlider(
                min: 0,
                max: widget.durationMs.toDouble(),
                values: RangeValues(_startMs, _endMs),
                onChanged: _onChanged,
                activeColor: BuddyColors.green,
                inactiveColor: BuddyColors.surfaceRaised,
              ),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(
                    'In ${_fmt(_startMs)}',
                    style: const TextStyle(color: BuddyColors.textPrimary, fontSize: 13),
                  ),
                  Text(
                    '${_fmt(_endMs - _startMs)} selected',
                    style: const TextStyle(
                      color: BuddyColors.textSecondary,
                      fontSize: 12,
                    ),
                  ),
                  Text(
                    'Out ${_fmt(_endMs)}',
                    style: const TextStyle(color: BuddyColors.textPrimary, fontSize: 13),
                  ),
                ],
              ),
              const SizedBox(height: 16),
              Row(
                children: [
                  Expanded(
                    child: TextButton(
                      onPressed: () => Navigator.of(context).pop(),
                      child: const Text('Cancel'),
                    ),
                  ),
                  const SizedBox(width: 8),
                  Expanded(
                    child: FilledButton(
                      style: FilledButton.styleFrom(
                        backgroundColor: BuddyColors.green,
                        foregroundColor: BuddyColors.black,
                      ),
                      onPressed: () => Navigator.of(context).pop((
                        start: _startMs.round(),
                        end: _endMs.round(),
                      )),
                      child: const Text('Save trim'),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _SoundSheet extends ConsumerStatefulWidget {
  final String? initialSelectedSoundId;

  const _SoundSheet({this.initialSelectedSoundId});

  @override
  ConsumerState<_SoundSheet> createState() => _SoundSheetState();
}

class _SoundSheetState extends ConsumerState<_SoundSheet> {
  final TextEditingController _searchController = TextEditingController();
  final Player _previewPlayer = Player();
  late String? _selectedId = widget.initialSelectedSoundId;
  String? _previewingId;
  double _volume = 100;

  @override
  void initState() {
    super.initState();
    _searchController.addListener(_onSearchChanged);
  }

  @override
  void dispose() {
    _searchController.removeListener(_onSearchChanged);
    _searchController.dispose();
    _previewPlayer.dispose();
    super.dispose();
  }

  Timer? _searchDebounce;
  void _onSearchChanged() {
    _searchDebounce?.cancel();
    _searchDebounce = Timer(const Duration(milliseconds: 350), () {
      ref.read(soundsProvider.notifier).load(query: _searchController.text.trim());
    });
  }

  Future<void> _preview(Sound sound) async {
    if (_previewingId == sound.id) {
      await _previewPlayer.pause();
      setState(() => _previewingId = null);
      return;
    }
    await _previewPlayer.setVolume(_volume);
    await _previewPlayer.open(Media(sound.audioUrl), play: true);
    setState(() => _previewingId = sound.id);
  }

  @override
  Widget build(BuildContext context) {
    final state = ref.watch(soundsProvider);
    return SafeArea(
      child: SizedBox(
        height: MediaQuery.sizeOf(context).height * 0.75,
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text(
                'Add sound',
                style: TextStyle(
                  color: BuddyColors.textPrimary,
                  fontWeight: FontWeight.w600,
                  fontSize: 16,
                ),
              ),
              const SizedBox(height: 12),
              TextField(
                controller: _searchController,
                style: const TextStyle(color: BuddyColors.textPrimary),
                decoration: const InputDecoration(
                  hintText: 'Search sounds…',
                  prefixIcon: Icon(Icons.search, color: BuddyColors.textSecondary),
                ),
              ),
              const SizedBox(height: 8),
              ListTile(
                contentPadding: EdgeInsets.zero,
                dense: true,
                leading: const Icon(Icons.volume_off_outlined, color: BuddyColors.textSecondary),
                title: const Text(
                  'Original only',
                  style: TextStyle(color: BuddyColors.textPrimary, fontSize: 14),
                ),
                trailing: _selectedId == null
                    ? const Icon(Icons.check, color: BuddyColors.green)
                    : null,
                onTap: () async {
                  await _previewPlayer.pause();
                  setState(() => _selectedId = null);
                  if (context.mounted) {
                    Navigator.of(context).pop((sound: null, volume: _volume));
                  }
                },
              ),
              const Divider(height: 1),
              Expanded(
                child: state.isLoading
                    ? const Center(
                        child: CircularProgressIndicator(color: BuddyColors.green),
                      )
                    : state.items.isEmpty
                        ? const Center(
                            child: Text(
                              'No sounds found',
                              style: TextStyle(color: BuddyColors.textSecondary),
                            ),
                          )
                        : ListView.separated(
                            itemCount: state.items.length,
                            separatorBuilder: (_, _) =>
                                const Divider(height: 1),
                            itemBuilder: (_, i) {
                              final sound = state.items[i];
                              final isPreviewing = _previewingId == sound.id;
                              return ListTile(
                                dense: true,
                                leading: Icon(
                                  isPreviewing
                                      ? Icons.pause_circle_outline
                                      : Icons.play_circle_outline,
                                  color: BuddyColors.green,
                                ),
                                title: Text(
                                  sound.name,
                                  maxLines: 1,
                                  overflow: TextOverflow.ellipsis,
                                  style: const TextStyle(
                                    color: BuddyColors.textPrimary,
                                    fontSize: 14,
                                  ),
                                ),
                                subtitle: Text(
                                  '${sound.artist} · ${sound.usageCount} uses',
                                  maxLines: 1,
                                  overflow: TextOverflow.ellipsis,
                                  style: const TextStyle(
                                    color: BuddyColors.textSecondary,
                                    fontSize: 12,
                                  ),
                                ),
                                onTap: () => _preview(sound),
                                trailing: _selectedId == sound.id
                                    ? const Icon(
                                        Icons.check_circle,
                                        color: BuddyColors.green,
                                      )
                                    : IconButton(
                                        icon: const Icon(
                                          Icons.add_circle_outline,
                                          color: BuddyColors.green,
                                        ),
                                        tooltip: 'Use sound',
                                        onPressed: () {
                                          setState(() => _selectedId = sound.id);
                                          Navigator.of(context).pop(
                                            (sound: sound, volume: _volume),
                                          );
                                        },
                                      ),
                              );
                            },
                          ),
              ),
              const Divider(height: 1),
              Row(
                children: [
                  const Icon(Icons.volume_up, color: BuddyColors.textSecondary, size: 20),
                  Expanded(
                    child: Slider(
                      value: _volume,
                      min: 0,
                      max: 100,
                      divisions: 100,
                      label: '${_volume.round()}',
                      activeColor: BuddyColors.green,
                      onChanged: (v) {
                        setState(() => _volume = v);
                        _previewPlayer.setVolume(v);
                      },
                    ),
                  ),
                  Text(
                    '${_volume.round()}',
                    style: const TextStyle(color: BuddyColors.textSecondary, fontSize: 12),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _AudienceSheet extends StatefulWidget {
  final String initialVisibility;
  final bool initialCommentsEnabled;

  const _AudienceSheet({
    required this.initialVisibility,
    required this.initialCommentsEnabled,
  });

  @override
  State<_AudienceSheet> createState() => _AudienceSheetState();
}

class _AudienceSheetState extends State<_AudienceSheet> {
  late String _visibility = widget.initialVisibility;
  late bool _commentsEnabled = widget.initialCommentsEnabled;

  String _label(String key) => switch (key) {
        'public' => 'Public — anyone on Buddy-Up',
        'buddies' => 'Buddies — your buddies only',
        'gym_members' => 'Gym members — your gyms',
        'private' => 'Private — only you',
        _ => key,
      };

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              'Audience',
              style: TextStyle(
                color: BuddyColors.textPrimary,
                fontWeight: FontWeight.w600,
                fontSize: 16,
              ),
            ),
            const SizedBox(height: 8),
            RadioGroup<String>(
              groupValue: _visibility,
              onChanged: (v) => setState(() => _visibility = v ?? _visibility),
              child: Column(
                children: visibilityOptions
                    .map((opt) => RadioListTile<String>(
                          value: opt,
                          title: Text(
                            _label(opt),
                            style: const TextStyle(
                              color: BuddyColors.textPrimary,
                              fontSize: 14,
                            ),
                          ),
                        ))
                    .toList(),
              ),
            ),
            const Divider(height: 1),
            SwitchListTile(
              contentPadding: EdgeInsets.zero,
              activeThumbColor: BuddyColors.green,
              title: const Text(
                'Allow comments',
                style: TextStyle(color: BuddyColors.textPrimary, fontSize: 14),
              ),
              subtitle: Text(
                _commentsEnabled ? 'Anyone can comment' : 'Comments are off',
                style: const TextStyle(color: BuddyColors.textSecondary, fontSize: 12),
              ),
              value: _commentsEnabled,
              onChanged: (v) => setState(() => _commentsEnabled = v),
            ),
            const SizedBox(height: 8),
            SizedBox(
              width: double.infinity,
              child: FilledButton(
                style: FilledButton.styleFrom(
                  backgroundColor: BuddyColors.green,
                  foregroundColor: BuddyColors.black,
                ),
                onPressed: () => Navigator.of(context).pop((
                  visibility: _visibility,
                  commentsEnabled: _commentsEnabled,
                )),
                child: const Text('Save'),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
