# Generated by Django 5.2.17 on 2026-09-03 15:53

import apps.guardians.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('revoked', 'Revoked')], default='pending', max_length=10)),
                ('invite_email', models.EmailField(max_length=254)),
                ('invite_token_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('permissions', models.JSONField(default=apps.guardians.models.default_permissions)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links_sent', to=settings.AUTH_USER_MODEL)),
                ('teen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guardians_guardian_link',
                'indexes': [models.Index(fields=['status'], name='guardians_g_status_ea0248_idx'), models.Index(fields=['teen'], name='guardians_g_teen_id_dc7251_idx')],
                'constraints': [models.UniqueConstraint(fields=('guardian', 'teen'), name='guardians_guardian_teen_unique')],
            },
        ),
    ]
