# Generated by Django 5.2.15 on 2026-06-23 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "diet_type",
                    models.CharField(
                        choices=[
                            ("vegan", "Vegan"),
                            ("keto", "Keto"),
                            ("balanced", "Balanced"),
                            ("high_protein", "High Protein"),
                            ("weight_loss", "Weight Loss"),
                            ("muscle_gain", "Muscle Gain"),
                            ("diabetic", "Diabetic-Friendly"),
                            ("vegetarian", "Vegetarian"),
                            ("paleo", "Paleo"),
                            ("gluten_free", "Gluten-Free"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duration_weeks", models.IntegerField(default=4)),
                ("calorie_range", models.CharField(blank=True, max_length=50)),
                ("price_artifacts", models.JSONField(default=dict)),
                ("preview_day", models.JSONField(default=dict)),
                ("full_plan", models.JSONField(default=dict)),
                ("shopping_list", models.JSONField(default=list)),
                ("is_published", models.BooleanField(default=True)),
                ("purchase_count", models.IntegerField(default=0)),
                ("average_rating", models.FloatField(default=0.0)),
                ("review_count", models.IntegerField(default=0)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_plans",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_meal_plan",
            },
        ),
        migrations.CreateModel(
            name="MealPlanPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tx_id", models.CharField(blank=True, max_length=100)),
                ("is_personalised", models.BooleanField(default=False)),
                ("personalised_data", models.JSONField(blank=True, null=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_plan_purchases",
                        to="profiles.profile",
                    ),
                ),
                (
                    "meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="marketplace.mealplan",
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_meal_plan_purchase",
            },
        ),
        migrations.CreateModel(
            name="MealPlanReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rating", models.IntegerField()),
                ("body", models.TextField(blank=True, max_length=500)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_plan_reviews",
                        to="profiles.profile",
                    ),
                ),
                (
                    "meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_list",
                        to="marketplace.mealplan",
                    ),
                ),
                (
                    "purchase",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="marketplace.mealplanpurchase",
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_meal_plan_review",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("brand", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("supplement", "Supplement"),
                            ("equipment", "Equipment"),
                            ("gear", "Gear"),
                            ("other", "Other"),
                        ],
                        default="supplement",
                        max_length=20,
                    ),
                ),
                ("image_url", models.URLField(blank=True)),
                ("affiliate_url", models.URLField()),
                ("price_display", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("click_count", models.IntegerField(default=0)),
                (
                    "recommended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommended_products",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_product",
            },
        ),
        migrations.CreateModel(
            name="TrainingProgramme",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(max_length=50)),
                ("duration_weeks", models.IntegerField(default=8)),
                ("price_artifacts", models.JSONField(default=dict)),
                ("is_published", models.BooleanField(default=True)),
                ("purchase_count", models.IntegerField(default=0)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_programmes",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_programme",
            },
        ),
        migrations.AddIndex(
            model_name="mealplan",
            index=models.Index(
                fields=["creator"], name="marketplace_creator_f24dd0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mealplan",
            index=models.Index(
                fields=["diet_type"], name="marketplace_diet_ty_f27977_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mealplan",
            index=models.Index(
                fields=["is_published", "-purchase_count"],
                name="marketplace_is_publ_f81412_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mealplanpurchase",
            unique_together={("meal_plan", "buyer")},
        ),
        migrations.AlterUniqueTogether(
            name="mealplanreview",
            unique_together={("purchase", "buyer")},
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category"], name="marketplace_categor_e01614_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active"], name="marketplace_is_acti_90c2f9_idx"
            ),
        ),
    ]
