# Generated by Django 5.2.15 on 2026-06-29 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_alter_mealplan_id_alter_product_id_and_more"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingProgrammePurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tx_id", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "db_table": "marketplace_programme_purchase",
            },
        ),
        migrations.CreateModel(
            name="TrainingProgrammeReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rating", models.IntegerField()),
                ("body", models.TextField(blank=True, max_length=500)),
            ],
            options={
                "db_table": "marketplace_programme_review",
            },
        ),
        migrations.AddIndex(
            model_name="trainingprogramme",
            index=models.Index(
                fields=["creator"], name="marketplace_creator_6e4e46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingprogramme",
            index=models.Index(
                fields=["category"], name="marketplace_categor_5908fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingprogramme",
            index=models.Index(
                fields=["is_published", "-purchase_count"],
                name="marketplace_is_publ_ae7cba_idx",
            ),
        ),
        migrations.AddField(
            model_name="trainingprogrammepurchase",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programme_purchases",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="trainingprogrammepurchase",
            name="programme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="marketplace.trainingprogramme",
            ),
        ),
        migrations.AddField(
            model_name="trainingprogrammereview",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programme_reviews",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="trainingprogrammereview",
            name="programme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews_list",
                to="marketplace.trainingprogramme",
            ),
        ),
        migrations.AddField(
            model_name="trainingprogrammereview",
            name="purchase",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="marketplace.trainingprogrammepurchase",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trainingprogrammepurchase",
            unique_together={("programme", "buyer")},
        ),
        migrations.AlterUniqueTogether(
            name="trainingprogrammereview",
            unique_together={("purchase", "buyer")},
        ),
    ]
