# Generated by Django 5.2.15 on 2026-07-04 21:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gyms", "0006_gymschedulepost_linked_live_and_more"),
        (
            "marketplace",
            "0003_trainingprogrammepurchase_trainingprogrammereview_and_more",
        ),
        ("profiles", "0002_profile_saved_payment_methods"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketplaceEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("cover_image_url", models.URLField(blank=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("in_person", "In Person"),
                            ("online", "Online"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="in_person",
                        max_length=15,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=300)),
                ("online_url", models.URLField(blank=True)),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("timezone", models.CharField(default="UTC", max_length=60)),
                ("capacity", models.IntegerField(default=0)),
                ("ticket_price_artifacts", models.JSONField(default=dict)),
                ("is_free", models.BooleanField(default=True)),
                ("is_published", models.BooleanField(default=True)),
                ("is_cancelled", models.BooleanField(default=False)),
                ("attendee_count", models.IntegerField(default=0)),
                ("tags", models.JSONField(default=list)),
                ("category", models.CharField(blank=True, max_length=50)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_events",
                        to="profiles.profile",
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="gyms.gym",
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_event",
                "ordering": ["start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="EventTicket",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ticket_code",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("tier", models.CharField(default="Standard", max_length=50)),
                ("price_paid_artifacts", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                            ("used", "Used"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("is_checked_in", models.BooleanField(default=False)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                (
                    "holder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_tickets",
                        to="profiles.profile",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="marketplace.marketplaceevent",
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_event_ticket",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="marketplaceevent",
            index=models.Index(
                fields=["creator"], name="marketplace_creator_1f91f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketplaceevent",
            index=models.Index(fields=["gym"], name="marketplace_gym_id_8912c6_idx"),
        ),
        migrations.AddIndex(
            model_name="marketplaceevent",
            index=models.Index(
                fields=["start_datetime", "is_published"],
                name="marketplace_start_d_851808_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eventticket",
            index=models.Index(
                fields=["holder"], name="marketplace_holder__e88ccf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventticket",
            index=models.Index(
                fields=["event", "holder"], name="marketplace_event_i_0b2c11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventticket",
            index=models.Index(
                fields=["ticket_code"], name="marketplace_ticket__a1ee3d_idx"
            ),
        ),
    ]
