# Generated by Django 5.2.15 on 2026-07-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0004_marketplaceevent_eventticket_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="cover_image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="trainingprogramme",
            name="cover_image_url",
            field=models.URLField(blank=True),
        ),
    ]
