# Generated by Django 5.2.15 on 2026-07-16 21:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0005_add_cover_image_url"),
        ("profiles", "0004_add_last_seen"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("discount_pct", models.IntegerField(default=0)),
                ("discount_artifacts", models.JSONField(default=dict)),
                ("usage_limit", models.IntegerField(default=0)),
                ("times_used", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_codes",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_discount_code",
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "buyer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_cart",
                        to="profiles.profile",
                    ),
                ),
                (
                    "discount_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="marketplace.discountcode",
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_cart",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("meal_plan", "Meal Plan"),
                            ("programme", "Training Programme"),
                            ("product", "Product"),
                            ("event_ticket", "Event Ticket"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="marketplace.cart",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplace.marketplaceevent",
                    ),
                ),
                (
                    "meal_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplace.mealplan",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplace.product",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marketplace.trainingprogramme",
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_cart_item",
                "unique_together": {
                    ("cart", "item_type", "meal_plan", "programme", "product", "event")
                },
            },
        ),
        migrations.AddIndex(
            model_name="discountcode",
            index=models.Index(fields=["code"], name="marketplace_code_3473cf_idx"),
        ),
        migrations.AddIndex(
            model_name="discountcode",
            index=models.Index(
                fields=["creator"], name="marketplace_creator_3b6765_idx"
            ),
        ),
    ]
