# Generated by Django 6.0.3 on 2026-07-27 13:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0006_discountcode_cart_cartitem_and_more"),
        ("profiles", "0004_add_last_seen"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountUsage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order_artifacts", models.JSONField(default=dict)),
                ("discount_pct_applied", models.IntegerField(default=0)),
                ("discount_artifacts_applied", models.JSONField(default=dict)),
                ("savings_artifacts", models.JSONField(default=dict)),
                (
                    "savings_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("was_successful", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "marketplace_discount_usage",
            },
        ),
        migrations.AddField(
            model_name="discountcode",
            name="campaign",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="code_type",
            field=models.CharField(
                choices=[("text", "Text Code"), ("qr", "QR Code")],
                default="text",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="description",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("percentage", "Percentage"),
                    ("fixed_artifacts", "Fixed Artifacts"),
                ],
                default="percentage",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="is_retired",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="max_uses_per_user",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="min_purchase_artifacts",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="qr_code",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="retired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="retired_reason",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="share_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="valid_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="valid_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="discountcode",
            index=models.Index(
                fields=["campaign"], name="marketplace_campaig_27a592_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discountcode",
            index=models.Index(
                fields=["valid_until"], name="marketplace_valid_u_aa7b22_idx"
            ),
        ),
        migrations.AddField(
            model_name="discountusage",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discount_usages",
                to="marketplace.cart",
            ),
        ),
        migrations.AddField(
            model_name="discountusage",
            name="discount",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usages",
                to="marketplace.discountcode",
            ),
        ),
        migrations.AddField(
            model_name="discountusage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discount_usages",
                to="profiles.profile",
            ),
        ),
        migrations.AddIndex(
            model_name="discountusage",
            index=models.Index(
                fields=["discount"], name="marketplace_discoun_7a70b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discountusage",
            index=models.Index(fields=["user"], name="marketplace_user_id_8a3009_idx"),
        ),
        migrations.AddIndex(
            model_name="discountusage",
            index=models.Index(
                fields=["created_at"], name="marketplace_created_d49d39_idx"
            ),
        ),
    ]
