# Generated by Django 6.0.3 on 2026-07-29 09:38

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gyms", "0006_gymschedulepost_linked_live_and_more"),
        ("marketplace", "0007_discountusage_discountcode_campaign_and_more"),
        ("profiles", "0005_profile_creator_balance_profile_creator_display_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopGymLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_primary", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "marketplace_shop_gym_link",
            },
        ),
        migrations.CreateModel(
            name="ShopMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("manager", "Manager"),
                            ("staff", "Staff"),
                        ],
                        default="owner",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_shop_membership",
            },
        ),
        migrations.CreateModel(
            name="ShopVerificationApplication",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("more_info_needed", "More Info Needed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fitness_trainer", "Fitness Trainer / Coach"),
                            ("nutritionist", "Nutritionist / Dietitian"),
                            ("wellness_coach", "Wellness Coach"),
                            ("physiotherapist", "Physiotherapist"),
                            ("sports_doctor", "Sports Doctor"),
                            ("gym_owner", "Gym Owner / Operator"),
                            ("content_creator", "Fitness Content Creator"),
                            ("equipment_retailer", "Equipment Retailer"),
                            ("other", "Other"),
                        ],
                        max_length=25,
                    ),
                ),
                ("legal_name", models.CharField(blank=True, max_length=200)),
                (
                    "business_registration_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("country", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "id_document",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="raw"
                    ),
                ),
                ("id_document_url", models.URLField(blank=True)),
                (
                    "professional_cert",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="raw"
                    ),
                ),
                ("professional_cert_url", models.URLField(blank=True)),
                ("additional_docs", models.JSONField(default=list)),
                ("website_url", models.URLField(blank=True)),
                ("social_proof_links", models.JSONField(default=list)),
                ("years_of_experience", models.IntegerField(blank=True, null=True)),
                ("specializations", models.JSONField(default=list)),
                ("bio_statement", models.TextField(blank=True)),
                ("agreed_to_creator_policy", models.BooleanField(default=False)),
                ("agreed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewer_notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
            ],
            options={
                "db_table": "marketplace_shop_verification_application",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="marketplaceevent",
            name="agenda",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="marketplaceevent",
            name="cancellation_policy",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="marketplaceevent",
            name="cover_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AddField(
            model_name="marketplaceevent",
            name="early_bird_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketplaceevent",
            name="early_bird_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="marketplaceevent",
            name="early_bird_price_artifacts",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="marketplaceevent",
            name="gallery_urls",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="marketplaceevent",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="marketplaceevent",
            name="location_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketplaceevent",
            name="location_lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketplaceevent",
            name="promo_video_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="marketplaceevent",
            name="recurrence",
            field=models.CharField(
                choices=[
                    ("none", "One-Time"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="marketplaceevent",
            name="ticket_tiers",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="allergen_flags",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="cover_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="macro_targets",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="meals_per_day",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="reminder_settings",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="rest_days",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="trailer_video_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="mealplanpurchase",
            name="reminder_settings",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="product",
            name="cover_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="gallery_urls",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="product",
            name="highlights",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="product",
            name="variants",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="trainingprogramme",
            name="cover_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AddField(
            model_name="trainingprogramme",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                    ("all_levels", "All Levels"),
                ],
                default="all_levels",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="trainingprogramme",
            name="equipment_list",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="trainingprogramme",
            name="fitness_goals",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="trainingprogramme",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trainingprogramme",
            name="notification_config",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="trainingprogramme",
            name="prerequisites",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="trainingprogramme",
            name="rest_days_pattern",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="trainingprogramme",
            name="schedule",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="trainingprogramme",
            name="sessions_per_week",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="trainingprogramme",
            name="trailer_video_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="trainingprogrammepurchase",
            name="notification_config",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("supplement", "Supplement"),
                    ("equipment", "Equipment"),
                    ("gear", "Gear"),
                    ("apparel", "Apparel"),
                    ("book", "Book / Guide"),
                    ("digital", "Digital Product"),
                    ("other", "Other"),
                ],
                default="supplement",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EventMedia",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=10
                    ),
                ),
                (
                    "file",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="file"
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("thumbnail_url", models.URLField(blank=True)),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="marketplace.marketplaceevent",
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_event_media",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgrammeActivityProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("activity_key", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_progress",
                        to="marketplace.trainingprogrammepurchase",
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_programme_activity_progress",
            },
        ),
        migrations.CreateModel(
            name="PushDevice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("fcm", "Firebase Cloud Messaging (Android/iOS)"),
                            ("web", "Web Push (Browser / PWA)"),
                            ("apns", "Apple Push Notification (APNS)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("token", models.TextField()),
                ("device_name", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_devices",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_push_device",
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("handle", models.SlugField(max_length=60, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fitness", "Fitness & Training"),
                            ("nutrition", "Nutrition & Meal Plans"),
                            ("wellness", "Wellness & Recovery"),
                            ("coaching", "Coaching & Mentoring"),
                            ("equipment", "Equipment & Gear"),
                            ("mixed", "Mixed / Multi-Category"),
                        ],
                        default="mixed",
                        max_length=20,
                    ),
                ),
                (
                    "logo",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
                (
                    "banner",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
                ("logo_url", models.URLField(blank=True)),
                ("banner_url", models.URLField(blank=True)),
                ("accent_color", models.CharField(default="#6366f1", max_length=7)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                ("website_url", models.URLField(blank=True)),
                ("social_links", models.JSONField(default=dict)),
                ("refund_policy", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("pending", "Pending Review"),
                            ("verified", "Verified / Buddy Up Certified"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        default="unverified",
                        max_length=15,
                    ),
                ),
                (
                    "verification_applied_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
            ],
            options={
                "db_table": "marketplace_shop",
                "indexes": [
                    models.Index(
                        fields=["handle"], name="marketplace_handle_ea84ed_idx"
                    ),
                    models.Index(
                        fields=["verification_status"],
                        name="marketplace_verific_08ad96_idx",
                    ),
                    models.Index(
                        fields=["category"], name="marketplace_categor_d2d293_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="marketplaceevent",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="marketplace.shop",
            ),
        ),
        migrations.AddField(
            model_name="mealplan",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="meal_plans",
                to="marketplace.shop",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="marketplace.shop",
            ),
        ),
        migrations.AddField(
            model_name="trainingprogramme",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="programmes",
                to="marketplace.shop",
            ),
        ),
        migrations.AddIndex(
            model_name="marketplaceevent",
            index=models.Index(fields=["shop"], name="marketplace_shop_id_9f1686_idx"),
        ),
        migrations.AddIndex(
            model_name="mealplan",
            index=models.Index(fields=["shop"], name="marketplace_shop_id_eba22a_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["shop"], name="marketplace_shop_id_3cdef3_idx"),
        ),
        migrations.AddIndex(
            model_name="trainingprogramme",
            index=models.Index(fields=["shop"], name="marketplace_shop_id_3a5c04_idx"),
        ),
        migrations.AddField(
            model_name="shopgymlink",
            name="gym",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_links",
                to="gyms.gym",
            ),
        ),
        migrations.AddField(
            model_name="shopgymlink",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gym_links",
                to="marketplace.shop",
            ),
        ),
        migrations.AddField(
            model_name="shopmembership",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_memberships",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="shopmembership",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="marketplace.shop",
            ),
        ),
        migrations.AddField(
            model_name="shopverificationapplication",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_applications",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="shopverificationapplication",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_applications",
                to="marketplace.shop",
            ),
        ),
        migrations.AddField(
            model_name="shopverificationapplication",
            name="submitted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cert_applications",
                to="profiles.profile",
            ),
        ),
        migrations.AddIndex(
            model_name="eventmedia",
            index=models.Index(
                fields=["event", "sort_order"], name="marketplace_event_i_f7938b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="programmeactivityprogress",
            index=models.Index(
                fields=["purchase", "status"], name="marketplace_purchas_2c04bb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="programmeactivityprogress",
            unique_together={("purchase", "activity_key")},
        ),
        migrations.AddIndex(
            model_name="pushdevice",
            index=models.Index(
                fields=["profile", "platform"], name="marketplace_profile_57a878_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pushdevice",
            index=models.Index(
                fields=["is_active"], name="marketplace_is_acti_1f1873_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pushdevice",
            unique_together={("profile", "token")},
        ),
        migrations.AlterUniqueTogether(
            name="shopgymlink",
            unique_together={("shop", "gym")},
        ),
        migrations.AlterUniqueTogether(
            name="shopmembership",
            unique_together={("shop", "profile")},
        ),
    ]
