# Generated by Django 6.0.8 on 2026-08-17 09:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_add_content_rating'),
        ('profiles', '0007_profile_content_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=40, unique=True)),
                ('fulfillment_type', models.CharField(choices=[('digital', 'Digital / Instant'), ('pickup', 'Pickup'), ('delivery', 'Delivery')], default='digital', max_length=10)),
                ('delivery_address', models.JSONField(default=dict)),
                ('pickup_details', models.JSONField(default=dict)),
                ('items_total_artifacts', models.JSONField(default=dict)),
                ('discount_artifacts', models.JSONField(default=dict)),
                ('total_artifacts', models.JSONField(default=dict)),
                ('spent_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('ready_for_pickup', 'Ready for Pickup'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='paid', max_length=20)),
                ('status_history', models.JSONField(default=list)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='profiles.profile')),
                ('discount_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.discountcode')),
            ],
            options={
                'db_table': 'marketplace_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderFulfillment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('carrier', models.CharField(blank=True, max_length=100)),
                ('tracking_number', models.CharField(blank=True, max_length=120)),
                ('tracking_url', models.URLField(blank=True)),
                ('pickup_location', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('timeline', models.JSONField(default=list)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('out_for_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('ready_for_pickup_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment_record', to='marketplace.order')),
            ],
            options={
                'db_table': 'marketplace_order_fulfillment',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('meal_plan', 'Meal Plan'), ('programme', 'Training Programme'), ('product', 'Product'), ('event_ticket', 'Event Ticket')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('price_artifacts', models.JSONField(default=dict)),
                ('paid_artifacts', models.JSONField(default=dict)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='profiles.profile')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.marketplaceevent')),
                ('meal_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.mealplan')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marketplace.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.product')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.trainingprogramme')),
            ],
            options={
                'db_table': 'marketplace_order_item',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer'], name='marketplace_buyer_i_fb6a9f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='marketplace_status_6b27f5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='marketplace_order_n_7aa3cb_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='marketplace_order_i_67767a_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['item_type'], name='marketplace_item_ty_808714_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['creator'], name='marketplace_creator_1f899a_idx'),
        ),
    ]
