# Generated by Django 5.2.16 on 2026-08-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_order_orderfulfillment_orderitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceevent',
            name='category',
            field=models.CharField(blank=True, choices=[('fitness', 'Fitness'), ('weightlifting', 'Weightlifting'), ('hiit', 'HIIT'), ('crossfit', 'CrossFit'), ('calisthenics', 'Calisthenics'), ('bodybuilding', 'Bodybuilding'), ('running', 'Running'), ('cycling', 'Cycling'), ('hiking', 'Hiking'), ('climbing', 'Climbing'), ('water_sports', 'Water Sports'), ('swimming', 'Swimming'), ('outdoor', 'Outdoor'), ('yoga', 'Yoga'), ('pilates', 'Pilates'), ('meditation', 'Meditation'), ('wellness', 'Wellness'), ('mental_health', 'Mental Health'), ('competition', 'Competition'), ('tournament', 'Tournament'), ('race', 'Race'), ('boxing', 'Boxing & MMA'), ('football', 'Football'), ('basketball', 'Basketball'), ('social', 'Social'), ('food_drink', 'Food & Drink'), ('networking', 'Networking'), ('nutrition', 'Nutrition'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('party', 'Party'), ('other', 'Other')], max_length=50),
        ),
    ]
