# Generated by Django 5.2.17 on 2026-10-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_commerce_readiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_modes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='fulfillment_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
