# Generated by Django 5.2.17 on 2026-10-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_product_delivery_modes_product_fulfillment_details'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'item_type', 'meal_plan', 'programme', 'product', 'event', 'meta')},
        ),
    ]
