# Generated by Django 5.2.17 on 2026-10-06 10:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0010_venuelocation_gyms_venue_geo_idx'),
        ('marketplace', '0015_alter_cartitem_unique_together_cartitem_meta_and_more'),
        ('profiles', '0013_buddyinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('more_info_needed', 'More Info Needed')], default='draft', max_length=20)),
                ('business_registration_number', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('opening_hours', models.JSONField(default=dict)),
                ('documents', models.JSONField(default=list)),
                ('agreed_to_policy', models.BooleanField(default=False)),
                ('agreed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'marketplace_station_application',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('artifacts', 'Artifacts (in-app)'), ('mpesa', 'M-Pesa'), ('card', 'Card')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='unpaid', max_length=10),
        ),
        migrations.CreateModel(
            name='DeliveryPersonnel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bicycle'), ('motorbike', 'Motorbike'), ('tuktuk', 'Tuk-tuk'), ('car', 'Car'), ('pickup', 'Pickup Truck'), ('lorry', 'Lorry / Truck')], default='bike', max_length=10)),
                ('service_zones', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('bio', models.TextField(blank=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_personnel', to='profiles.profile')),
            ],
            options={
                'db_table': 'marketplace_delivery_personnel',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='marketplace.deliverypersonnel'),
        ),
        migrations.CreateModel(
            name='DeliveryPersonnelApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bicycle'), ('motorbike', 'Motorbike'), ('tuktuk', 'Tuk-tuk'), ('car', 'Car'), ('pickup', 'Pickup Truck'), ('lorry', 'Lorry / Truck')], default='bike', max_length=10)),
                ('service_zones', models.JSONField(default=list)),
                ('id_document_url', models.URLField(blank=True)),
                ('licence_document_url', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('more_info_needed', 'More Info Needed')], default='draft', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_personnel_applications', to='profiles.profile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_delivery_personnel_applications', to='profiles.profile')),
            ],
            options={
                'db_table': 'marketplace_delivery_personnel_application',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('flutterwave', 'Flutterwave')], default='flutterwave', max_length=30)),
                ('method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Card')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=5)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initiated', max_length=25)),
                ('raw_response', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to='profiles.profile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='marketplace.order')),
            ],
            options={
                'db_table': 'marketplace_payment_intent',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickupStation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('opening_hours', models.JSONField(default=dict)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('owner_type', models.CharField(blank=True, choices=[('shop', 'Shop'), ('gym', 'Gym')], max_length=10)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_stations', to='gyms.gym')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_stations', to='marketplace.shop')),
            ],
            options={
                'db_table': 'marketplace_pickup_station',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='marketplace.pickupstation'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='mkt_order_payment_status_idx'),
        ),
        migrations.AddField(
            model_name='stationapplication',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station_applications', to='gyms.gym'),
        ),
        migrations.AddField(
            model_name='stationapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_station_applications', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='stationapplication',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station_applications', to='marketplace.shop'),
        ),
        migrations.AddField(
            model_name='stationapplication',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_applications', to='profiles.profile'),
        ),
        migrations.AddIndex(
            model_name='deliverypersonnel',
            index=models.Index(fields=['is_active', 'vehicle_type'], name='mkt_deliverypers_active_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverypersonnelapplication',
            index=models.Index(fields=['status', '-created_at'], name='mkt_delapp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['order', '-created_at'], name='mkt_paymentintent_order_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['status'], name='mkt_paymentintent_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='mkt_paymentintent_amt_gt0'),
        ),
        migrations.AddIndex(
            model_name='pickupstation',
            index=models.Index(fields=['is_active', 'latitude', 'longitude'], name='mkt_pickstation_geo_idx'),
        ),
        migrations.AddConstraint(
            model_name='pickupstation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('gym__isnull', True), ('shop__isnull', False)), models.Q(('gym__isnull', False), ('shop__isnull', True)), _connector='OR'), name='mkt_pickstation_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='pickupstation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('shop',), name='mkt_pickstation_pri_shop_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pickupstation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('gym',), name='mkt_pickstation_pri_gym_uniq'),
        ),
        migrations.AddIndex(
            model_name='stationapplication',
            index=models.Index(fields=['status', '-created_at'], name='mkt_stationapp_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='stationapplication',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('gym__isnull', True), ('shop__isnull', False)), models.Q(('gym__isnull', False), ('shop__isnull', True)), _connector='OR'), name='mkt_stationapp_one_owner'),
        ),
    ]
