# Generated by Django 5.2.15 on 2026-06-23 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("push_enabled", models.BooleanField(default=True)),
                ("email_enabled", models.BooleanField(default=True)),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("buddy_request_push", models.BooleanField(default=True)),
                ("buddy_accepted_push", models.BooleanField(default=True)),
                ("new_follower_push", models.BooleanField(default=False)),
                ("comment_push", models.BooleanField(default=False)),
                ("live_starting_push", models.BooleanField(default=True)),
                ("session_reminder_push", models.BooleanField(default=True)),
                ("streak_milestone_push", models.BooleanField(default=True)),
                ("accountability_ping_push", models.BooleanField(default=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "notifications_preference",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("buddy_request", "Buddy Request"),
                            ("buddy_accepted", "Buddy Accepted"),
                            ("buddy_declined", "Buddy Declined"),
                            ("new_follower", "New Follower"),
                            ("comment", "Comment"),
                            ("comment_reply", "Comment Reply"),
                            ("post_reaction", "Post Reaction"),
                            ("post_repost", "Post Repost"),
                            ("post_quote", "Post Quote"),
                            ("live_starting", "Live Starting"),
                            ("gym_invite", "Gym Invite"),
                            ("session_booked", "Session Booked"),
                            ("session_reminder", "Session Reminder"),
                            ("session_cancelled", "Session Cancelled"),
                            ("payment_received", "Payment Received"),
                            ("withdrawal_processed", "Withdrawal Processed"),
                            ("streak_milestone", "Streak Milestone"),
                            ("streak_reminder", "Streak Reminder"),
                            ("verification_update", "Verification Update"),
                            ("accountability_ping", "Accountability Ping"),
                            ("new_device_login", "New Device Login"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                ("metadata", models.JSONField(default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("is_pushed", models.BooleanField(default=False)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "notifications_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="notificatio_recipie_a972ce_idx",
                    ),
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="notificatio_recipie_4e3567_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="notificatio_notific_f2898f_idx",
                    ),
                ],
            },
        ),
    ]
