# Generated by Django 6.0.3 on 2026-08-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="meal_reminder_push",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="new_purchase_push",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="programme_reminder_push",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="shop_cert_push",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("buddy_request", "Buddy Request"),
                    ("buddy_accepted", "Buddy Accepted"),
                    ("buddy_declined", "Buddy Declined"),
                    ("new_follower", "New Follower"),
                    ("comment", "Comment"),
                    ("comment_reply", "Comment Reply"),
                    ("post_reaction", "Post Reaction"),
                    ("post_repost", "Post Repost"),
                    ("post_quote", "Post Quote"),
                    ("live_starting", "Live Starting"),
                    ("gym_invite", "Gym Invite"),
                    ("session_booked", "Session Booked"),
                    ("session_reminder", "Session Reminder"),
                    ("session_cancelled", "Session Cancelled"),
                    ("payment_received", "Payment Received"),
                    ("withdrawal_processed", "Withdrawal Processed"),
                    ("streak_milestone", "Streak Milestone"),
                    ("streak_reminder", "Streak Reminder"),
                    ("verification_update", "Verification Update"),
                    ("accountability_ping", "Accountability Ping"),
                    ("new_device_login", "New Device Login"),
                    ("shop_created", "Shop Created"),
                    ("shop_verified", "Shop Verified"),
                    ("shop_cert_status", "Shop Certification Status Update"),
                    ("programme_reminder", "Programme Activity Reminder"),
                    ("meal_reminder", "Meal Plan Daily Reminder"),
                    ("new_purchase", "New Purchase"),
                    ("shop_invite", "Shop Invite"),
                ],
                max_length=30,
            ),
        ),
    ]
