# Generated by Django 5.2.16 on 2026-08-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('buddy_request', 'Buddy Request'), ('buddy_accepted', 'Buddy Accepted'), ('buddy_declined', 'Buddy Declined'), ('new_follower', 'New Follower'), ('comment', 'Comment'), ('comment_reply', 'Comment Reply'), ('post_reaction', 'Post Reaction'), ('post_repost', 'Post Repost'), ('post_quote', 'Post Quote'), ('live_starting', 'Live Starting'), ('live_reminder', 'Live Reminder'), ('gym_invite', 'Gym Invite'), ('session_booked', 'Session Booked'), ('session_reminder', 'Session Reminder'), ('session_cancelled', 'Session Cancelled'), ('payment_received', 'Payment Received'), ('withdrawal_processed', 'Withdrawal Processed'), ('streak_milestone', 'Streak Milestone'), ('streak_reminder', 'Streak Reminder'), ('verification_update', 'Verification Update'), ('accountability_ping', 'Accountability Ping'), ('new_device_login', 'New Device Login'), ('shop_created', 'Shop Created'), ('shop_verified', 'Shop Verified'), ('shop_cert_status', 'Shop Certification Status Update'), ('programme_reminder', 'Programme Activity Reminder'), ('meal_reminder', 'Meal Plan Daily Reminder'), ('new_purchase', 'New Purchase'), ('shop_invite', 'Shop Invite'), ('community_invite', 'Community Invite'), ('community_member', 'New Community Member'), ('community_post', 'Community Post'), ('community_comment', 'Community Comment'), ('community_reaction', 'Community Reaction'), ('community_join_request', 'Community Join Request'), ('community_join_approved', 'Community Join Approved'), ('repost', 'Post Repost'), ('mention', 'Mention'), ('event_ticket_purchased', 'Event Ticket Purchased'), ('order_status_changed', 'Order Status Changed'), ('payout_processed', 'Payout Processed')], max_length=30),
        ),
    ]
