# Generated by Django 5.2.17 on 2026-10-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_notificationpreference_buddy_nearby_push_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='order_status_changed_push',
            field=models.BooleanField(default=True),
        ),
    ]
