# Generated by Django 5.2.15 on 2026-06-23 15:02

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("username", models.CharField(max_length=30, unique=True)),
                ("display_name", models.CharField(max_length=50)),
                ("bio", models.CharField(blank=True, max_length=200)),
                ("avatar_url", models.URLField(blank=True)),
                ("cover_url", models.URLField(blank=True)),
                ("pronouns", models.CharField(blank=True, max_length=30)),
                ("location_city", models.CharField(blank=True, max_length=100)),
                ("location_country", models.CharField(blank=True, max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "Regular User"),
                            ("trainer", "Personal Trainer"),
                            ("practitioner", "Health Practitioner"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                ("is_anonymous_posting", models.BooleanField(default=False)),
                ("show_active_status", models.BooleanField(default=True)),
                ("streak_days", models.IntegerField(default=0)),
                ("streak_last_activity", models.DateField(blank=True, null=True)),
                ("artifact_balance", models.JSONField(default=dict)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("email", "Email Verified"),
                            ("id", "ID Verified"),
                            ("trainer", "Certified Trainer"),
                            ("practitioner", "Health Practitioner"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "privacy_level",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="public",
                        max_length=10,
                    ),
                ),
                ("external_link", models.URLField(blank=True)),
                ("workout_schedule", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "profiles_profile",
                "indexes": [
                    models.Index(
                        fields=["username"], name="profiles_pr_usernam_b7f118_idx"
                    ),
                    models.Index(fields=["role"], name="profiles_pr_role_cee16c_idx"),
                    models.Index(
                        fields=["verification_status"],
                        name="profiles_pr_verific_5ba44f_idx",
                    ),
                    models.Index(
                        fields=["location_city", "location_country"],
                        name="profiles_pr_locatio_8711c6_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SharedGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("target", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "buddies",
                    models.ManyToManyField(
                        related_name="shared_goals", to="profiles.profile"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals_created",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "profiles_shared_goal",
            },
        ),
        migrations.CreateModel(
            name="FollowRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "followee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="profiles.profile",
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "profiles_follow_relationship",
                "indexes": [
                    models.Index(
                        fields=["follower"], name="profiles_fo_followe_90e806_idx"
                    ),
                    models.Index(
                        fields=["followee"], name="profiles_fo_followe_d9ce02_idx"
                    ),
                ],
                "unique_together": {("follower", "followee")},
            },
        ),
        migrations.CreateModel(
            name="BuddyRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buddy_sent",
                        to="profiles.profile",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buddy_received",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "profiles_buddy_relationship",
                "indexes": [
                    models.Index(
                        fields=["from_user", "status"],
                        name="profiles_bu_from_us_32e792_idx",
                    ),
                    models.Index(
                        fields=["to_user", "status"],
                        name="profiles_bu_to_user_4c031b_idx",
                    ),
                ],
                "unique_together": {("from_user", "to_user")},
            },
        ),
        migrations.CreateModel(
            name="BlockRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blocked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks_received",
                        to="profiles.profile",
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks_made",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "profiles_block_relationship",
                "unique_together": {("blocker", "blocked")},
            },
        ),
        migrations.CreateModel(
            name="AccountabilityPing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.CharField(
                        default="How's your workout going? 💪", max_length=100
                    ),
                ),
                ("responded", models.BooleanField(default=False)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pings_sent",
                        to="profiles.profile",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pings_received",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "profiles_accountability_ping",
                "indexes": [
                    models.Index(
                        fields=["to_user", "-created_at"],
                        name="profiles_ac_to_user_c10e5f_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "created_at__date",
                                django.db.models.functions.datetime.Now(),
                            )
                        ),
                        fields=("from_user", "to_user"),
                        name="one_ping_per_buddy_per_day",
                    )
                ],
            },
        ),
    ]
