# Generated by Django 6.0.3 on 2026-07-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_add_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="creator_balance",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="profile",
            name="creator_display_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
