# Generated by Django 5.2.16 on 2026-08-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_creator_balance_profile_creator_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('none', 'None'), ('email', 'Email Verified'), ('id', 'ID Verified'), ('trainer', 'Certified Trainer'), ('practitioner', 'Health Practitioner'), ('shop', 'Verified Shop'), ('gym', 'Verified Gym')], default='none', max_length=20),
        ),
    ]
