# Generated by Django 5.2.17 on 2026-10-04 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_recommendationfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuddySearchProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='search_profile', serialize=False, to='profiles.profile')),
                ('intents', models.JSONField(blank=True, default=list)),
                ('modes', models.JSONField(blank=True, default=list)),
                ('neighbourhood', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_updated_at', models.DateTimeField(blank=True, null=True)),
                ('search_radius_km', models.FloatField(blank=True, null=True)),
                ('available_now', models.BooleanField(default=False)),
                ('available_until', models.DateTimeField(blank=True, null=True)),
                ('pace', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'profiles_buddy_search_profile',
                'indexes': [models.Index(fields=['available_now'], name='profiles_bu_availab_875880_idx'), models.Index(fields=['latitude', 'longitude'], name='profiles_bu_latitud_7400e4_idx')],
            },
        ),
    ]
