# Generated by Django 5.2.17 on 2026-10-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_buddysearchprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddysearchprofile',
            name='age_band',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='buddysearchprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='buddysearchprofile',
            name='custom_intent',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='buddysearchprofile',
            name='dob_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='buddysearchprofile',
            name='goals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='buddysearchprofile',
            name='incognito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buddysearchprofile',
            name='photos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='buddysearchprofile',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('buddies', 'Buddies only'), ('hidden', 'Hidden')], default='public', max_length=10),
        ),
    ]
