# Generated by Django 5.2.17 on 2026-10-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_buddysearchprofile_age_band_buddysearchprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddysearchprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
