# Generated by Django 5.2.17 on 2026-10-05 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_buddysearchprofile_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuddyInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests_sent', to='profiles.profile')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests_received', to='profiles.profile')),
            ],
            options={
                'db_table': 'profiles_buddy_interest',
                'indexes': [models.Index(fields=['to_user'], name='profiles_bu_to_user_b47304_idx'), models.Index(fields=['from_user'], name='profiles_bu_from_us_888df7_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='buddy_interest_not_self')],
                'unique_together': {('from_user', 'to_user')},
            },
        ),
    ]
