# Generated by Django 5.2.15 on 2026-06-23 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsyncProgramme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("duration_weeks", models.IntegerField()),
                ("price_artifacts", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("enrolled_count", models.IntegerField(default=0)),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programmes",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "sessions_programme",
            },
        ),
        migrations.CreateModel(
            name="BookingSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("1on1_live", "1:1 Live"),
                            ("group_live", "Group Live"),
                            ("async", "Async Programme"),
                            ("nutrition", "Nutrition Consultation"),
                            ("in_person", "In-Person"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled_by_client", "Cancelled by Client"),
                            ("cancelled_by_trainer", "Cancelled by Trainer"),
                            ("disputed", "Disputed"),
                            ("no_show", "No Show"),
                        ],
                        default="pending",
                        max_length=25,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.IntegerField(default=60)),
                ("artifact_fee", models.JSONField(default=dict)),
                ("notes", models.TextField(blank=True, max_length=300)),
                ("escrow_tx_id", models.CharField(blank=True, max_length=100)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings_as_client",
                        to="profiles.profile",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings_as_trainer",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "sessions_booking",
            },
        ),
        migrations.CreateModel(
            name="ProgrammeEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_weeks", models.JSONField(default=list)),
                ("progress_pct", models.IntegerField(default=0)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="profiles.profile",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="booking_sessions.asyncprogramme",
                    ),
                ),
            ],
            options={
                "db_table": "sessions_enrollment",
            },
        ),
        migrations.CreateModel(
            name="ProgrammeWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("week_number", models.IntegerField()),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("video_url", models.URLField(blank=True)),
                ("pdf_url", models.URLField(blank=True)),
                ("exercises", models.JSONField(default=list)),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weeks",
                        to="booking_sessions.asyncprogramme",
                    ),
                ),
            ],
            options={
                "db_table": "sessions_programme_week",
                "ordering": ["week_number"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rating", models.IntegerField()),
                ("body", models.TextField(blank=True, max_length=500)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_given",
                        to="profiles.profile",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="booking_sessions.bookingsession",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_received",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "sessions_review",
            },
        ),
        migrations.CreateModel(
            name="TrainerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("specialties", models.JSONField(default=list)),
                ("certifications", models.JSONField(default=list)),
                ("years_experience", models.IntegerField(default=0)),
                ("languages", models.JSONField(default=list)),
                ("session_types", models.JSONField(default=list)),
                ("pricing", models.JSONField(default=dict)),
                ("average_rating", models.FloatField(default=0.0)),
                ("review_count", models.IntegerField(default=0)),
                ("total_sessions_completed", models.IntegerField(default=0)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_profile",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "sessions_trainer_profile",
            },
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("day_of_week", models.IntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("buffer_minutes", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to="booking_sessions.trainerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "sessions_availability",
            },
        ),
        migrations.AddIndex(
            model_name="bookingsession",
            index=models.Index(
                fields=["client", "status"], name="sessions_bo_client__bf967b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingsession",
            index=models.Index(
                fields=["trainer", "status"], name="sessions_bo_trainer_337b57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingsession",
            index=models.Index(
                fields=["scheduled_at"], name="sessions_bo_schedul_785e5b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="programmeenrollment",
            unique_together={("client", "programme")},
        ),
        migrations.AlterUniqueTogether(
            name="programmeweek",
            unique_together={("programme", "week_number")},
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["trainer"], name="sessions_re_trainer_156501_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("session", "client")},
        ),
        migrations.AlterUniqueTogether(
            name="availability",
            unique_together={("trainer", "day_of_week", "start_time")},
        ),
    ]
