# Generated by Django 6.0.3 on 2026-07-27 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_sessions", "0002_alter_bookingsession_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingsession",
            name="parent_series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurring_sessions",
                to="booking_sessions.bookingsession",
            ),
        ),
        migrations.AddField(
            model_name="bookingsession",
            name="recurrence_pattern",
            field=models.CharField(
                blank=True,
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
