# Generated by Django 5.2.17 on 2026-09-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_sessions', '0004_booking_completion_and_charging'),
        ('profiles', '0009_recommendationfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='intro_video_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='is_mobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='is_virtual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='trainerprofile',
            index=models.Index(fields=['is_mobile', 'is_virtual'], name='sessions_tr_is_mobi_325414_idx'),
        ),
        migrations.AddIndex(
            model_name='trainerprofile',
            index=models.Index(fields=['-average_rating', '-review_count'], name='sessions_tr_average_38cfd7_idx'),
        ),
    ]
