# Generated by Django 5.2.15 on 2026-07-16 13:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_alter_conversation_id_alter_message_id"),
        ("profiles", "0003_profile_locked_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="call_in_progress",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="conversation",
            name="group_avatar_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="message",
            name="deleted_for",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="message",
            name="file_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="message",
            name="media_mime",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="message",
            name="media_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("photo", "Photo"),
                    ("video", "Video"),
                    ("voice", "Voice Note"),
                    ("document", "Document"),
                    ("location", "Location"),
                    ("workout_log", "Workout Log"),
                    ("meal_plan", "Meal Plan"),
                    ("artifact_tip", "Artifact Tip"),
                    ("accountability_ping", "Accountability Ping"),
                    ("call_log", "Call Log"),
                ],
                default="text",
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="CallLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "call_type",
                    models.CharField(
                        choices=[("audio", "Audio"), ("video", "Video")],
                        default="audio",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("ringing", "Ringing"),
                            ("answered", "Answered"),
                            ("declined", "Declined"),
                            ("missed", "Missed"),
                            ("ended", "Ended"),
                        ],
                        default="initiated",
                        max_length=15,
                    ),
                ),
                ("duration_seconds", models.IntegerField(default=0)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "callee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls_received",
                        to="profiles.profile",
                    ),
                ),
                (
                    "caller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls_made",
                        to="profiles.profile",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_logs",
                        to="messaging.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "messaging_call_log",
                "indexes": [
                    models.Index(
                        fields=["conversation", "-created_at"],
                        name="messaging_c_convers_45ef08_idx",
                    ),
                    models.Index(
                        fields=["caller"], name="messaging_c_caller__dddda8_idx"
                    ),
                    models.Index(
                        fields=["callee"], name="messaging_c_callee__feaff5_idx"
                    ),
                ],
            },
        ),
    ]
