# Generated by Django 5.2.15 on 2026-07-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0003_add_callog_media_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("photo", "Photo"),
                    ("video", "Video"),
                    ("voice", "Voice Note"),
                    ("document", "Document"),
                    ("location", "Location"),
                    ("poll", "Poll"),
                    ("event", "Event"),
                    ("workout_log", "Workout Log"),
                    ("meal_plan", "Meal Plan"),
                    ("artifact_tip", "Artifact Tip"),
                    ("accountability_ping", "Accountability Ping"),
                    ("call_log", "Call Log"),
                ],
                default="text",
                max_length=25,
            ),
        ),
    ]
