# Generated by Django 6.0.8 on 2026-08-17 11:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_message_message_type'),
        ('profiles', '0007_profile_content_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='cover_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='invite_code',
            field=models.CharField(blank=True, db_index=True, max_length=12),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_community',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True, max_length=1000)),
                ('media_mime', models.CharField(blank=True, max_length=100)),
                ('is_pinned', models.BooleanField(default=False)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to='profiles.profile')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to='messaging.conversation')),
            ],
            options={
                'db_table': 'messaging_community_post',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPostComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_post_comments', to='profiles.profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='messaging.communitypost')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='messaging.communitypostcomment')),
            ],
            options={
                'db_table': 'messaging_community_post_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='messaging.communitypost')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_post_likes', to='profiles.profile')),
            ],
            options={
                'db_table': 'messaging_community_post_like',
            },
        ),
        migrations.CreateModel(
            name='ConversationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='messaging.conversation')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_memberships', to='profiles.profile')),
            ],
            options={
                'db_table': 'messaging_conversation_membership',
            },
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['conversation', '-created_at'], name='messaging_c_convers_920d31_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['conversation', 'author'], name='messaging_c_convers_0336a3_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypostcomment',
            index=models.Index(fields=['post', 'created_at'], name='messaging_c_post_id_2b7cf1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communitypostlike',
            unique_together={('post', 'profile')},
        ),
        migrations.AlterUniqueTogether(
            name='conversationmembership',
            unique_together={('conversation', 'profile')},
        ),
    ]
