# Generated by Django 5.2.17 on 2026-10-05 16:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_callsession_callparticipant'),
        ('profiles', '0013_buddyinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='origin',
            field=models.CharField(choices=[('direct', 'Direct'), ('discovery', 'Discovery'), ('buddy', 'Buddy'), ('group', 'Group'), ('community', 'Community')], db_index=True, default='direct', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='promoted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ConversationPromotion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='messaging.conversation')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_promotions', to='profiles.profile')),
            ],
            options={
                'db_table': 'messaging_conversation_promotion',
            },
        ),
    ]
