# Generated by Django 5.2.17 on 2026-10-09 00:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountActionRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ban', 'Ban Account'), ('suspension', 'Suspend Account'), ('verification_decision', 'Verification Decision'), ('payout', 'Payout'), ('staff_role_grant', 'Grant Staff Role')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('requested_by_profile', models.CharField(blank=True, max_length=120)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('requires_second', models.BooleanField(default=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_requests_raised', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governance_action_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'governance_account_action_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='governance__status_8b3326_idx'), models.Index(fields=['target_user', '-created_at'], name='governance__target__8bbb8e_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('moderator', 'Moderator'), ('support', 'Support Agent'), ('gym_relations', 'Gym Relations'), ('supplier_relations', 'Supplier Relations'), ('logistics', 'Logistics'), ('finance', 'Finance'), ('verification_regulator', 'Verification Regulator')], max_length=32)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_roles_granted', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'governance_staff_role',
                'indexes': [models.Index(fields=['role'], name='governance__role_dc52ad_idx'), models.Index(fields=['revoked_at'], name='governance__revoked_bc64c5_idx')],
            },
        ),
    ]
