# Generated by Django 5.2.17 on 2026-09-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('source', models.CharField(default='landing', max_length=40)),
            ],
            options={
                'db_table': 'waitlist_entry',
                'ordering': ['-created_at'],
            },
        ),
    ]
