# Generated by Django 5.2.17 on 2026-09-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='country',
            field=models.CharField(blank=True, default='', max_length=56),
        ),
    ]
