# Generated by Django 5.2.17 on 2026-09-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0002_waitlistentry_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='interest',
            field=models.CharField(choices=[('user', 'User'), ('gym', 'Gym'), ('trainer', 'Trainer')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
