# Generated by Django 5.2.17 on 2026-09-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0003_waitlistentry_interest_waitlistentry_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.CharField(choices=[('general', 'General'), ('support', 'Support'), ('gyms', 'Gyms & Partnerships'), ('trainers', 'Trainers'), ('press', 'Press')], default='general', max_length=20)),
                ('subject', models.CharField(blank=True, default='', max_length=120)),
                ('message', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='new', max_length=20)),
            ],
            options={
                'db_table': 'waitlist_contact_inquiry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=2000)),
                ('category', models.CharField(choices=[('gyms', 'Gyms'), ('trainers', 'Trainers'), ('events', 'Events'), ('programmes', 'Programmes'), ('analytics', 'Analytics'), ('app', 'App Experience'), ('other', 'Other')], default='other', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('name', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('planned', 'Planned'), ('shipped', 'Shipped'), ('declined', 'Declined')], default='new', max_length=20)),
            ],
            options={
                'db_table': 'waitlist_feature_suggestion',
                'ordering': ['-created_at'],
            },
        ),
    ]
