# Generated by Django 5.2.17 on 2026-09-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0004_contactinquiry_featuresuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistentry',
            name='interest',
            field=models.CharField(choices=[('user', 'User'), ('gym', 'Gym'), ('trainer', 'Trainer'), ('corporate', 'Corporate')], default='user', max_length=20),
        ),
    ]
