# Generated by Django 5.2.17 on 2026-09-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0005_alter_waitlistentry_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistentry',
            name='interest',
            field=models.CharField(choices=[('user', 'User'), ('gym', 'Gym'), ('trainer', 'Trainer'), ('corporate', 'Corporate'), ('organiser', 'Event Organiser'), ('supplier', 'Supplier / Shop'), ('distributor', 'Distributor')], default='user', max_length=20),
        ),
    ]
