# Generated by Django 5.2.17 on 2026-09-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0006_alter_waitlistentry_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=120)),
                ('portfolio_url', models.URLField(blank=True, default='')),
                ('message', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('interview', 'Interview'), ('offer', 'Offer'), ('declined', 'Declined')], default='new', max_length=20)),
            ],
            options={
                'db_table': 'waitlist_career_application',
                'ordering': ['-created_at'],
            },
        ),
    ]
