# Generated by Django 5.2.17 on 2026-09-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0007_careerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerapplication',
            name='resume_url',
            field=models.CharField(blank=True, default='', help_text='Supabase Storage path of the uploaded resume.', max_length=300),
        ),
    ]
