# Generated by Django 5.2.16 on 2026-08-10 17:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0005_profile_creator_balance_profile_creator_display_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('id_card', 'ID Card'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('certification', 'Professional Certification'), ('proof_of_address', 'Proof of Address'), ('selfie', 'Selfie'), ('other', 'Other')], max_length=25)),
                ('file_url', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, max_length=500)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to='profiles.profile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_type', models.CharField(choices=[('id', 'ID Verification'), ('trainer', 'Trainer Certification'), ('practitioner', 'Health Practitioner'), ('shop', 'Shop / Seller Verification'), ('gym', 'Gym Verification')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=12)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('credential_title', models.CharField(blank=True, max_length=120)),
                ('credential_issuer', models.CharField(blank=True, max_length=200)),
                ('credential_id', models.CharField(blank=True, max_length=120)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('scope_of_practice', models.CharField(blank=True, choices=[('general_fitness', 'General Fitness Coaching'), ('nutrition_wellness', 'General Wellness Nutrition'), ('meal_planning', 'Meal Planning (General Wellness)'), ('medical_nutrition', 'Medical Nutrition Therapy'), ('physical_therapy', 'Physiotherapy / Rehab'), ('clinical', 'Clinical Practice')], max_length=30)),
                ('documents', models.ManyToManyField(related_name='submissions', to='verification.verificationdocument')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_submissions', to='profiles.profile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_submission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='verificationdocument',
            index=models.Index(fields=['profile', 'document_type'], name='verificatio_profile_1633f6_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationdocument',
            index=models.Index(fields=['status'], name='verificatio_status_30d8c6_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationsubmission',
            index=models.Index(fields=['profile', 'status'], name='verificatio_profile_871c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationsubmission',
            index=models.Index(fields=['verification_type'], name='verificatio_verific_72979a_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationsubmission',
            index=models.Index(fields=['-created_at'], name='verificatio_created_5a0e48_idx'),
        ),
    ]
