# Generated by Django 5.2.17 on 2026-08-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationsubmission',
            name='completed_steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='verificationsubmission',
            name='current_step',
            field=models.CharField(blank=True, choices=[('id_document', 'ID Document'), ('selfie_liveness', 'Selfie / Liveness Check'), ('face_match', 'Face Match'), ('review', 'Review & Submit'), ('done', 'Done')], max_length=20),
        ),
        migrations.AddField(
            model_name='verificationsubmission',
            name='face_match_score',
            field=models.FloatField(blank=True, help_text='Similarity confidence from the face-match backend (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='verificationsubmission',
            name='face_match_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('auto_matched', 'Auto Matched'), ('manual_review', 'Manual Review'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=15),
        ),
    ]
