# Generated by Django 5.2.17 on 2026-09-22 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0010_venuelocation_gyms_venue_geo_idx'),
        ('verification', '0004_document_retention_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationsubmission',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_submissions', to='gyms.gym'),
        ),
    ]
