# Generated by Django 5.2.17 on 2026-08-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_prediction_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aipredictionjob',
            name='task',
            field=models.CharField(choices=[('food_recognition', 'Food Recognition'), ('text_moderation', 'Text Moderation'), ('image_moderation', 'Image Moderation'), ('embedding', 'Embedding'), ('meal_plan_personalisation', 'Meal Plan Personalisation'), ('meal_plan_personalise', 'Meal Plan Personalise'), ('workout_analysis', 'Workout Analysis'), ('health_insights', 'Health Insights'), ('form_analyzer', 'Form Analyzer'), ('feed_ranking', 'Feed Ranking'), ('video_description', 'Workout Video Description'), ('summarization', 'Text Summarization'), ('text_to_speech', 'Text To Speech'), ('visual_search_embedding', 'Visual Search Embedding'), ('transcription', 'Transcription')], max_length=40),
        ),
    ]
