# Generated by Django 5.2.16 on 2026-08-06 05:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFlag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flag_reason', models.CharField(choices=[('nsfw', 'NSFW'), ('toxic', 'Toxic Language'), ('spam', 'Spam'), ('misinfo', 'Misinformation'), ('custom', 'Custom Rule')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('confidence', models.FloatField(default=0.0)),
                ('source', models.CharField(default='auto', max_length=50)),
                ('content_type', models.CharField(max_length=50)),
                ('content_id', models.CharField(max_length=100)),
                ('content_preview', models.TextField(blank=True, max_length=500)),
                ('is_actioned', models.BooleanField(default=False)),
                ('action_taken', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'moderation_content_flag',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'content_id'], name='moderation__content_2d241c_idx'), models.Index(fields=['flag_reason'], name='moderation__flag_re_5ec364_idx'), models.Index(fields=['severity'], name='moderation__severit_4568b3_idx'), models.Index(fields=['-created_at'], name='moderation__created_110531_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModerationReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('hate_speech', 'Hate Speech'), ('nudity', 'Nudity / Sexual Content'), ('violence', 'Violence'), ('misinformation', 'Misinformation'), ('impersonation', 'Impersonation'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('content_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=15)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moderation_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('warning', 'Warning'), ('content_removed', 'Content Removed'), ('user_suspended', 'User Suspended'), ('user_banned', 'User Banned'), ('report_dismissed', 'Report Dismissed')], max_length=25)),
                ('reason', models.TextField()),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions_received', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='moderation.moderationreport')),
            ],
            options={
                'db_table': 'moderation_action',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='moderationreport',
            index=models.Index(fields=['status'], name='moderation__status_3fc7e7_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationreport',
            index=models.Index(fields=['reason'], name='moderation__reason_460c2e_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationreport',
            index=models.Index(fields=['-created_at'], name='moderation__created_6c20ed_idx'),
        ),
    ]
