# Generated by Django 5.2.16 on 2026-08-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentflag',
            name='flag_reason',
            field=models.CharField(choices=[('nsfw', 'NSFW'), ('toxic', 'Toxic Language'), ('spam', 'Spam'), ('misinfo', 'Misinformation'), ('medical_claim', 'Medical / Treatment Claim'), ('undisclosed_sponsor', 'Undisclosed Sponsorship'), ('custom', 'Custom Rule')], max_length=20),
        ),
    ]
