# Generated by Django 5.2.16 on 2026-08-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_alter_contentflag_flag_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentflag',
            name='flag_reason',
            field=models.CharField(choices=[('nsfw', 'NSFW'), ('toxic', 'Toxic Language'), ('spam', 'Spam'), ('misinfo', 'Misinformation'), ('medical_claim', 'Medical / Treatment Claim'), ('undisclosed_sponsor', 'Undisclosed Sponsorship'), ('adult_ungated', 'Adult Content Outside Mature Category'), ('custom', 'Custom Rule')], max_length=20),
        ),
        migrations.AlterField(
            model_name='moderationreport',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('hate_speech', 'Hate Speech'), ('nudity', 'Nudity / Sexual Content'), ('adult_ungated', 'Adult Content Outside Mature Category'), ('violence', 'Violence'), ('misinformation', 'Misinformation'), ('impersonation', 'Impersonation'), ('other', 'Other')], max_length=30),
        ),
    ]
