# Generated by Django 5.2.17 on 2026-10-09 01:06

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_login_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountevent',
            name='event_type',
            field=models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login Failed'), ('account_suspended', 'Account Suspended'), ('account_banned', 'Account Banned'), ('account_standing_lifted', 'Account Standing Lifted'), ('mfa_enrolment_required', 'MFA Enrolment Required'), ('login_new_device', 'Login from New Device'), ('login_new_country', 'Login from New Country'), ('password_changed', 'Password Changed'), ('email_changed', 'Email Changed'), ('2fa_enabled', '2FA Enabled'), ('2fa_disabled', '2FA Disabled'), ('passkey_registered', 'Passkey Registered'), ('passkey_renamed', 'Passkey Renamed'), ('passkey_revoked', 'Passkey Revoked'), ('security_notification_sent', 'Security Notification Sent'), ('account_deactivated', 'Account Deactivated'), ('account_reactivated', 'Account Reactivated'), ('account_deleted', 'Account Deleted'), ('post_created', 'Post Created'), ('post_deleted', 'Post Deleted'), ('buddy_request_sent', 'Buddy Request Sent'), ('buddy_request_accepted', 'Buddy Request Accepted'), ('profile_updated', 'Profile Updated'), ('avatar_updated', 'Avatar Updated'), ('comment_added', 'Comment Added'), ('reaction_added', 'Reaction Added'), ('live_started', 'Live Started'), ('session_booked', 'Session Booked'), ('marketplace_purchase', 'Marketplace Purchase'), ('wallet_transaction', 'Wallet Transaction')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='totp_secret',
            field=apps.accounts.models.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='AccountStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('clear', 'Clear'), ('warned', 'Warned'), ('suspended', 'Suspended'), ('banned', 'Banned')], default='clear', max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('action_id', models.CharField(blank=True, max_length=64)),
                ('suspended_until', models.DateTimeField(blank=True, null=True)),
                ('permanent', models.BooleanField(default=False)),
                ('is_moderation_action', models.BooleanField(default=False)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_standing_actions_issued', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_standing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_account_standing',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['state', '-issued_at'], name='accounts_ac_state_bd7ddc_idx')],
            },
        ),
    ]
