# Generated by Django 5.2.15 on 2026-06-23 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtifactTransaction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("tip_sent", "Tip Sent"),
                            ("tip_received", "Tip Received"),
                            ("live_fee", "Live Fee"),
                            ("gym_subscription", "Gym Subscription"),
                            ("session_fee", "Session Fee"),
                            ("marketplace", "Marketplace"),
                            ("withdrawal", "Withdrawal"),
                            ("platform_cut", "Platform Cut"),
                            ("refund", "Refund"),
                            ("bonus", "Bonus"),
                        ],
                        max_length=20,
                    ),
                ),
                ("artifact_type", models.CharField(max_length=30)),
                ("quantity", models.IntegerField()),
                (
                    "direction",
                    models.CharField(
                        choices=[("credit", "Credit"), ("debit", "Debit")],
                        max_length=10,
                    ),
                ),
                ("reference_id", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("held", "Held (Escrow)"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "fiat_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("fiat_currency", models.CharField(default="KES", max_length=5)),
                ("payment_provider", models.CharField(blank=True, max_length=30)),
                ("clearance_at", models.DateTimeField(blank=True, null=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "counterparty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="counterparty_transactions",
                        to="profiles.profile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "wallet_artifact_transaction",
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="wallet_arti_user_id_5e1f3e_idx",
                    ),
                    models.Index(
                        fields=["transaction_type"],
                        name="wallet_arti_transac_b5adb5_idx",
                    ),
                    models.Index(
                        fields=["status"], name="wallet_arti_status_0d66a7_idx"
                    ),
                    models.Index(
                        fields=["counterparty"], name="wallet_arti_counter_2b0de9_idx"
                    ),
                ],
            },
        ),
    ]
