# Generated by Django 5.2.15 on 2026-06-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_alter_artifacttransaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifacttransaction",
            name="bank_account",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="artifacttransaction",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="artifacttransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("purchase", "Purchase"),
                    ("tip_sent", "Tip Sent"),
                    ("tip_received", "Tip Received"),
                    ("gift_sent", "Gift Sent"),
                    ("gift_received", "Gift Received"),
                    ("live_fee", "Live Fee"),
                    ("gym_subscription", "Gym Subscription"),
                    ("session_fee", "Session Fee"),
                    ("marketplace", "Marketplace"),
                    ("withdrawal", "Withdrawal"),
                    ("platform_cut", "Platform Cut"),
                    ("refund", "Refund"),
                    ("bonus", "Bonus"),
                ],
                max_length=20,
            ),
        ),
    ]
