# Generated by Django 5.2.15 on 2026-06-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_artifacttransaction_bank_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifacttransaction",
            name="flutterwave_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="artifacttransaction",
            name="flutterwave_response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artifacttransaction",
            name="tx_ref",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
