# Generated by Django 6.0.3 on 2026-08-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_artifacttransaction_flutterwave_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifacttransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("purchase", "Purchase"),
                    ("tip_sent", "Tip Sent"),
                    ("tip_received", "Tip Received"),
                    ("gift_sent", "Gift Sent"),
                    ("gift_received", "Gift Received"),
                    ("live_fee", "Live Fee"),
                    ("gym_subscription", "Gym Subscription"),
                    ("session_fee", "Session Fee"),
                    ("marketplace", "Marketplace"),
                    ("withdrawal", "Withdrawal"),
                    ("platform_cut", "Platform Cut"),
                    ("refund", "Refund"),
                    ("bonus", "Bonus"),
                    ("creator_transfer", "Creator Wallet Transfer"),
                ],
                max_length=20,
            ),
        ),
    ]
