# Generated by Django 5.2.17 on 2026-09-17 22:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0009_recommendationfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmSound',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('source', models.CharField(choices=[('upload', 'Upload'), ('voice_note', 'Voice Note'), ('suggestion', 'Suggestion')], default='upload', max_length=12)),
                ('audio', models.FileField(blank=True, null=True, upload_to='alarm_sounds/')),
                ('audio_url', models.URLField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('buddies', 'Buddies')], default='private', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_sounds', to='profiles.profile')),
            ],
            options={
                'db_table': 'alarms_sound',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('days_mask', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(127)])),
                ('label', models.CharField(blank=True, max_length=80)),
                ('enabled', models.BooleanField(default=True)),
                ('snooze_minutes', models.PositiveSmallIntegerField(default=5)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='profiles.profile')),
                ('sound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarms', to='alarms.alarmsound')),
            ],
            options={
                'db_table': 'alarms_alarm',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='AlarmSuggestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('note', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('dismissed', 'Dismissed')], default='pending', max_length=10)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_suggestions_received', to='profiles.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_suggestions_sent', to='profiles.profile')),
            ],
            options={
                'db_table': 'alarms_suggestion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlarmShare',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_shares_received', to='profiles.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_shares_sent', to='profiles.profile')),
                ('sound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='alarms.alarmsound')),
            ],
            options={
                'db_table': 'alarms_share',
                'ordering': ['-created_at'],
                'unique_together': {('sound', 'recipient')},
            },
        ),
    ]
