# Generated by Django 5.2.17 on 2026-08-25 16:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0008_onboarding_consent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('icon', models.CharField(default='🏆', max_length=40)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=10)),
                ('category', models.CharField(choices=[('activity', 'Activity & Training'), ('nutrition', 'Nutrition'), ('social', 'Social & Community'), ('live', 'Live & Sessions'), ('consistency', 'Consistency')], default='activity', max_length=15)),
                ('metric', models.CharField(help_text='Metric key evaluated by services.py', max_length=50)),
                ('threshold', models.FloatField(help_text='Value the metric must reach to unlock')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'gamification_achievement_definition',
                'ordering': ['sort_order', 'threshold'],
                'indexes': [models.Index(fields=['is_active', 'category'], name='gamificatio_is_acti_367fc7_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress', models.FloatField(default=0.0, help_text='Metric value at last evaluation')),
                ('earned_at', models.DateTimeField(blank=True, null=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='gamification.achievementdefinition')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='profiles.profile')),
            ],
            options={
                'db_table': 'gamification_user_achievement',
                'ordering': ['-earned_at', '-created_at'],
                'indexes': [models.Index(fields=['profile', '-earned_at'], name='gamificatio_profile_debda9_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'definition'), name='uniq_profile_achievement')],
            },
        ),
    ]
