import React from 'react';
import ReactDOM from 'react-dom/client';
import { App } from './App';
import './styles/globals.css';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);

// The single service worker (/sw.js — generated by vite-plugin-pwa, which
// imports the web-push handlers from /service-worker-push.js) registers
// itself. Registering a second SW here would race for scope '/' and break
// either push or offline caching.
