import React from 'react';
import ReactDOM from 'react-dom/client';
import { App } from './App';
import { initReducedMotion } from './lib/reducedMotion';
import './styles/globals.css';

initReducedMotion();

// Escape hatch for clients pinned by a stale/broken service worker:
// opening any URL with ?clear-sw=1 unregisters every SW, wipes all
// caches, then reloads clean. Shareable as a support link — no manual
// site-data archaeology required.
if (typeof window !== 'undefined' && new URLSearchParams(window.location.search).has('clear-sw')) {
  (async () => {
    try {
      if ('serviceWorker' in navigator) {
        const regs = await navigator.serviceWorker.getRegistrations();
        await Promise.all(regs.map((r) => r.unregister()));
      }
      if ('caches' in window) {
        const keys = await caches.keys();
        await Promise.all(keys.map((k) => caches.delete(k)));
      }
    } finally {
      const url = new URL(window.location.href);
      url.searchParams.delete('clear-sw');
      window.location.replace(url.toString());
    }
  })();
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);

// The single service worker (/sw.js — generated by vite-plugin-pwa, which
// imports the web-push handlers from /service-worker-push.js) registers
// itself. Registering a second SW here would race for scope '/' and break
// either push or offline caching.
