import React from 'react';
import ReactDOM from 'react-dom/client';
import { registerSW } from 'virtual:pwa-register';
import { App } from './App';
import { initReducedMotion } from './lib/reducedMotion';
import './styles/globals.css';

initReducedMotion();

// Triage diagnostics: which build is running, and which worker (if any)
// controls this page. Read via DevTools console when reporting issues.
if (typeof window !== 'undefined') {
  const controllerURL =
    ('serviceWorker' in navigator && navigator.serviceWorker.controller?.scriptURL) || 'none';
  // eslint-disable-next-line no-console
  console.info(`[buddyup] build=${__BUILD_TIME__} sw-controller=${controllerURL}`);
}

// Register the single service worker (/sw.js — generated by vite-plugin-pwa,
// which imports the web-push handlers from /service-worker-push.js).
// Re-registering here (not relying on any legacy registration) is what
// actually installs AND updates the worker: without this call, returning
// visitors keep whatever worker they installed months ago forever.
// `immediate: true` checks for an update on every page load; the hourly
// interval catches long-lived sessions.
const updateSW = registerSW({
  immediate: true,
  onNeedRefresh() {
    window.dispatchEvent(new CustomEvent('buddyup:sw-update'));
  },
  onOfflineReady() {
    window.dispatchEvent(new CustomEvent('buddyup:sw-ready'));
  },
});
setInterval(() => {
  updateSW(true).catch(() => undefined);
}, 60 * 60 * 1000);

// Escape hatch for clients pinned by a stale/broken service worker:
// opening any URL with ?clear-sw=1 unregisters every SW, wipes all
// caches, then reloads clean. Shareable as a support link — no manual
// site-data archaeology required.
if (typeof window !== 'undefined' && new URLSearchParams(window.location.search).has('clear-sw')) {
  (async () => {
    try {
      if ('serviceWorker' in navigator) {
        const regs = await navigator.serviceWorker.getRegistrations();
        await Promise.all(regs.map((r) => r.unregister()));
      }
      if ('caches' in window) {
        const keys = await caches.keys();
        await Promise.all(keys.map((k) => caches.delete(k)));
      }
    } finally {
      const url = new URL(window.location.href);
      url.searchParams.delete('clear-sw');
      window.location.replace(url.toString());
    }
  })();
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
