# Generated by Django 5.2.15 on 2026-06-23 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gyms", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuddyLive",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=80)),
                (
                    "live_type",
                    models.CharField(
                        choices=[
                            ("open_sweat", "Open Sweat"),
                            ("buddy_circle", "Buddy Circle"),
                            ("gym_live", "Gym Live"),
                            ("pt_session_live", "PT Session Live"),
                            ("random_drop", "Random Drop"),
                            ("practitioner_live", "Practitioner Live"),
                        ],
                        max_length=20,
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                (
                    "access",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("buddies", "Buddies Only"),
                            ("gym_members", "Gym Members"),
                        ],
                        default="public",
                        max_length=15,
                    ),
                ),
                ("artifact_fee", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("live", "Live"),
                            ("ended", "Ended"),
                        ],
                        default="scheduled",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("viewer_peak", models.IntegerField(default=0)),
                ("replay_url", models.URLField(blank=True)),
                ("replay_saved", models.BooleanField(default=False)),
                ("agora_channel", models.CharField(blank=True, max_length=100)),
                ("mux_asset_id", models.CharField(blank=True, max_length=100)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("is_recurring", models.BooleanField(default=False)),
                ("recurrence_rule", models.CharField(blank=True, max_length=200)),
                ("equipment_list", models.JSONField(default=list)),
                (
                    "co_hosts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="co_hosted_lives",
                        to="profiles.profile",
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lives",
                        to="gyms.gym",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_lives",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "lives_buddy_live",
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_for"],
                        name="lives_buddy_status_135c25_idx",
                    ),
                    models.Index(
                        fields=["live_type"], name="lives_buddy_live_ty_ce6d8d_idx"
                    ),
                    models.Index(
                        fields=["host", "-created_at"],
                        name="lives_buddy_host_id_9560c7_idx",
                    ),
                    models.Index(
                        fields=["gym", "status"], name="lives_buddy_gym_id_780763_idx"
                    ),
                ],
            },
        ),
    ]
