# Generated by Django 5.2.15 on 2026-06-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lives", "0002_alter_buddylive_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="buddylive",
            name="mux_playback_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
