# Generated by Django 5.2.15 on 2026-06-25 15:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lives", "0003_buddylive_mux_playback_id"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveRSVP",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "live",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvps",
                        to="lives.buddylive",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_rsvps",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "lives_rsvp",
                "unique_together": {("live", "user")},
            },
        ),
    ]
