# Generated by Django 5.2.15 on 2026-06-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lives", "0004_liversvp"),
    ]

    operations = [
        migrations.AddField(
            model_name="buddylive",
            name="client_recording_session_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="buddylive",
            name="livekit_egress_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
