# Generated by Django 5.2.15 on 2026-06-28 09:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lives", "0005_buddylive_client_recording_session_id_and_more"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveAttendee",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("host", "Host"),
                            ("co_host", "Co-Host"),
                            ("attendee", "Attendee"),
                        ],
                        default="attendee",
                        max_length=10,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                (
                    "live",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendees",
                        to="lives.buddylive",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_attendances",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Live Attendee",
                "verbose_name_plural": "Live Attendees",
                "db_table": "lives_attendee",
                "indexes": [
                    models.Index(
                        fields=["live", "-joined_at"],
                        name="lives_atten_live_id_ff8ada_idx",
                    ),
                    models.Index(
                        fields=["user", "-joined_at"],
                        name="lives_atten_user_id_99f1cd_idx",
                    ),
                ],
            },
        ),
    ]
