# Generated by Django 5.2.15 on 2026-08-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lives", "0006_liveattendee"),
    ]

    operations = [
        migrations.AddField(
            model_name="buddylive",
            name="recording_consent",
            field=models.CharField(
                choices=[
                    ("auto_record", "Auto-record for replays"),
                    ("opt_out", "Opt out of auto-recording"),
                ],
                default="auto_record",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="buddylive",
            name="reminders_sent",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="liversvp",
            name="fee_paid",
            field=models.JSONField(default=dict),
        ),
    ]
