# Generated by Django 5.2.16 on 2026-08-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lives', '0009_liveattendee_unique_and_dedupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddylive',
            name='live_type',
            field=models.CharField(choices=[('open_sweat', 'Open Sweat'), ('buddy_circle', 'Buddy Circle'), ('gym_live', 'Gym Live'), ('pt_session_live', 'PT Session Live'), ('random_drop', 'Random Drop'), ('practitioner_live', 'Practitioner Live'), ('audio', 'Audio Live')], max_length=20),
        ),
    ]
