# Generated by Django 5.2.17 on 2026-09-29 09:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lives', '0010_alter_buddylive_live_type'),
        ('profiles', '0009_recommendationfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveReplayView',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=1)),
                ('live', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replay_views', to='lives.buddylive')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_replay_views', to='profiles.profile')),
            ],
            options={
                'db_table': 'lives_replay_view',
                'indexes': [models.Index(fields=['live', '-created_at'], name='lives_repla_live_id_b52577_idx'), models.Index(fields=['viewer', '-created_at'], name='lives_repla_viewer__16018f_idx')],
                'unique_together': {('live', 'viewer')},
            },
        ),
    ]
