# Generated by Django 5.2.15 on 2026-06-23 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gyms", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField()),
                ("is_anonymous", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="profiles.profile",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="feed.comment",
                    ),
                ),
            ],
            options={
                "db_table": "feed_comment",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("photo", "Photo"),
                            ("short_video", "Short Video (BuddyClip)"),
                            ("long_video", "Long Video (BuddySession)"),
                            ("workout_log", "Workout Log"),
                            ("meal", "Meal"),
                            ("progress", "Progress"),
                            ("moment", "Moment (Story)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("body", models.TextField(blank=True)),
                ("is_anonymous", models.BooleanField(default=False)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("buddies", "Buddies Only"),
                            ("gym_members", "Gym Members"),
                            ("private", "Private"),
                        ],
                        default="public",
                        max_length=15,
                    ),
                ),
                ("is_repost", models.BooleanField(default=False)),
                ("quote_body", models.TextField(blank=True)),
                ("location_label", models.CharField(blank=True, max_length=200)),
                ("workout_log_data", models.JSONField(blank=True, null=True)),
                ("meal_data", models.JSONField(blank=True, null=True)),
                ("progress_data", models.JSONField(blank=True, null=True)),
                ("media_urls", models.JSONField(default=list)),
                ("tags", models.JSONField(default=list)),
                ("view_count", models.IntegerField(default=0)),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[
                            ("clean", "Clean"),
                            ("flagged", "Flagged"),
                            ("removed", "Removed"),
                            ("reviewed", "Reviewed"),
                        ],
                        default="clean",
                        max_length=15,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="profiles.profile",
                    ),
                ),
                (
                    "gym_tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tagged_posts",
                        to="gyms.gym",
                    ),
                ),
                (
                    "original_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reposts",
                        to="feed.post",
                    ),
                ),
                (
                    "pinned_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pinned_on",
                        to="feed.comment",
                    ),
                ),
            ],
            options={
                "db_table": "feed_post",
            },
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="feed.post",
            ),
        ),
        migrations.CreateModel(
            name="Reaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("pump", "Pump 💪"),
                            ("fire", "Fire 🔥"),
                            ("respect", "Respect 🤝"),
                            ("grind", "Grind 😤"),
                            ("lets_go", "Let's Go 🏋️"),
                            ("haha", "Haha 😂"),
                            ("too_hard", "Too Hard 💀"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="profiles.profile",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="feed.comment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="feed.post",
                    ),
                ),
            ],
            options={
                "db_table": "feed_reaction",
            },
        ),
        migrations.CreateModel(
            name="Save",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("collection", models.CharField(blank=True, max_length=100)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saves",
                        to="feed.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saves",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "feed_save",
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["author", "-created_at"], name="feed_post_author__c854fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["post_type"], name="feed_post_post_ty_378be6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["visibility", "moderation_status"],
                name="feed_post_visibil_1764d2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["gym_tag", "-created_at"], name="feed_post_gym_tag_2f74b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["post", "-created_at"], name="feed_commen_post_id_4006fb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                fields=("post", "author", "reaction_type"), name="unique_post_reaction"
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                fields=("comment", "author", "reaction_type"),
                name="unique_comment_reaction",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="save",
            unique_together={("user", "post")},
        ),
    ]
