# Generated by Django 5.2.15 on 2026-07-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_alter_post_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
    ]
