# Generated by Django 5.2.15 on 2026-07-02 06:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0003_post_is_pinned"),
        ("profiles", "0002_profile_saved_payment_methods"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="mentioned_profiles",
            field=models.ManyToManyField(
                blank=True, related_name="mention_posts", to="profiles.profile"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("photo", "Photo"),
                    ("short_video", "Short Video (BuddyClip)"),
                    ("long_video", "Long Video (BuddySession)"),
                    ("workout_log", "Workout Log"),
                    ("meal", "Meal"),
                    ("progress", "Progress"),
                    ("moment", "Moment (Story)"),
                    ("poll", "Poll"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Poll",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.CharField(max_length=300)),
                ("closes_at", models.DateTimeField(blank=True, null=True)),
                ("allow_multiple", models.BooleanField(default=False)),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poll",
                        to="feed.post",
                    ),
                ),
            ],
            options={
                "db_table": "feed_poll",
            },
        ),
        migrations.CreateModel(
            name="PollOption",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="feed.poll",
                    ),
                ),
            ],
            options={
                "db_table": "feed_poll_option",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PollVote",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="feed.polloption",
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="feed.poll",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poll_votes",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "feed_poll_vote",
                "unique_together": {("poll", "voter", "option")},
            },
        ),
    ]
