# Generated by Django 5.2.15 on 2026-07-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0004_add_mentions_and_polls"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedPost",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("feed.post",),
        ),
        migrations.CreateModel(
            name="GymPost",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("feed.post",),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="reaction_type",
            field=models.CharField(max_length=20),
        ),
    ]
