# Generated by Django 5.2.15 on 2026-07-06 12:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0005_feedpost_gympost_alter_reaction_reaction_type"),
        ("gyms", "0006_gymschedulepost_linked_live_and_more"),
        ("profiles", "0003_profile_locked_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Draft",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("photo", "Photo"),
                            ("short_video", "Short Video (BuddyClip)"),
                            ("long_video", "Long Video (BuddySession)"),
                            ("workout_log", "Workout Log"),
                            ("meal", "Meal"),
                            ("progress", "Progress"),
                            ("moment", "Moment (Story)"),
                            ("poll", "Poll"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("body", models.TextField(blank=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("buddies", "Buddies Only"),
                            ("gym_members", "Gym Members"),
                            ("private", "Private"),
                        ],
                        default="public",
                        max_length=15,
                    ),
                ),
                ("location_label", models.CharField(blank=True, max_length=200)),
                ("media_urls", models.JSONField(default=list)),
                ("tags", models.JSONField(default=list)),
                ("poll_question", models.CharField(blank=True, max_length=300)),
                ("poll_options", models.JSONField(default=list)),
                ("poll_allow_multiple", models.BooleanField(default=False)),
                ("mentioned_user_ids", models.JSONField(default=list)),
                ("is_anonymous", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafts",
                        to="profiles.profile",
                    ),
                ),
                (
                    "gym_tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drafts",
                        to="gyms.gym",
                    ),
                ),
            ],
            options={
                "db_table": "feed_draft",
                "indexes": [
                    models.Index(
                        fields=["author", "-updated_at"],
                        name="feed_draft_author__bad8d5_idx",
                    )
                ],
            },
        ),
    ]
