# Generated by Django 5.2.16 on 2026-08-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
