# Generated by Django 5.2.16 on 2026-08-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_post_content_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='location_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
