# Generated by Django 5.2.16 on 2026-08-21 18:11 (revised v3: cascade-delete dependents)

from django.db import migrations, connection


def deduplicate_reposts(apps, schema_editor):
    """
    Remove duplicate repost rows (same author + original_post) using raw SQL.
    Keeps the newest row. Cascade-deletes FK-dependent rows first (reactions,
    comments, saves) so the post deletion doesn't violate FK constraints.
    """
    with connection.cursor() as cursor:
        # Collect IDs of older duplicates (keep newest per author+original_post)
        cursor.execute("""
            SELECT id FROM (
                SELECT id,
                       ROW_NUMBER() OVER (
                           PARTITION BY author_id, original_post_id
                           ORDER BY created_at DESC
                       ) AS rn
                FROM feed_post
                WHERE is_repost = TRUE AND original_post_id IS NOT NULL
            ) sub
            WHERE rn > 1
        """)
        dupe_ids = [str(row[0]) for row in cursor.fetchall()]

        if not dupe_ids:
            return

        # Use a CTE-based delete to cascade dependents automatically
        # via temporary disabling FK checks or explicit deletion order
        placeholders = ','.join([f"'{pid}'" for pid in dupe_ids])

        # Delete FK dependents first
        cursor.execute(f"DELETE FROM feed_reaction WHERE post_id::text IN ({placeholders})")
        cursor.execute(f"DELETE FROM feed_comment WHERE post_id::text IN ({placeholders})")

        # Check and delete saved posts if table exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_schema = 'public' AND table_name = 'feed_savedpost'
            )
        """)
        if cursor.fetchone()[0]:
            cursor.execute(f"DELETE FROM feed_savedpost WHERE post_id::text IN ({placeholders})")

        # Check and delete poll votes if table exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_schema = 'public' AND table_name = 'feed_pollvote'
            )
        """)
        if cursor.fetchone()[0]:
            cursor.execute(f"DELETE FROM feed_pollvote WHERE post_id::text IN ({placeholders})")

        # Now safe to delete the duplicate post rows
        cursor.execute(f"DELETE FROM feed_post WHERE id::text IN ({placeholders})")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    # Run as non-atomic so dedup SQL and ALTER TABLE run in separate transactions,
    # avoiding "pending trigger events" error from PostgreSQL.
    atomic = False

    dependencies = [
        ('feed', '0009_post_location_lat_post_location_lng'),
        ('profiles', '0007_profile_content_rating'),
    ]

    operations = [
        # Step 1: deduplicate existing rows (cascade-deletes dependents first)
        migrations.RunPython(deduplicate_reposts, noop),
        # Step 2: now safe to add the unique constraint
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('author', 'original_post')},
        ),
    ]
