# Generated by Django 5.2.17 on 2026-08-29 13:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_post_client_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('artist', models.CharField(blank=True, max_length=120)),
                ('audio_url', models.URLField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('curated', 'Curated'), ('original', 'Original')], default='curated', max_length=20)),
                ('license', models.CharField(default='CC0', max_length=60)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('original_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_sounds', to='feed.post')),
            ],
            options={
                'db_table': 'feed_sound',
            },
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], default='image', max_length=10)),
                ('url', models.URLField(max_length=1000)),
                ('poster_url', models.URLField(blank=True, max_length=1000)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('trim_start_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('trim_end_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('sound_volume', models.PositiveSmallIntegerField(default=100)),
                ('captions', models.JSONField(blank=True, default=list)),
                ('captions_vtt', models.TextField(blank=True)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='feed.post')),
                ('sound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_media', to='feed.sound')),
            ],
            options={
                'db_table': 'feed_post_media',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='sound',
            index=models.Index(fields=['source'], name='feed_sound_source_870cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='sound',
            index=models.Index(fields=['usage_count'], name='feed_sound_usage_c_ab3d10_idx'),
        ),
        migrations.AddIndex(
            model_name='postmedia',
            index=models.Index(fields=['post', 'order'], name='feed_post_m_post_id_9e80d7_idx'),
        ),
    ]
