# Generated by Django 5.2.17 on 2026-09-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_backfill_postmedia_from_media_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='edit_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
