# Generated by Django 5.2.17 on 2026-09-14 08:48

import apps.feed.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_post_share_count'),
        ('profiles', '0009_recommendationfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostShare',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=apps.feed.models._share_code, max_length=16, unique=True)),
                ('channel', models.CharField(choices=[('native', 'Native sheet'), ('copy', 'Copy link'), ('whatsapp', 'WhatsApp'), ('x', 'X'), ('facebook', 'Facebook'), ('telegram', 'Telegram'), ('other', 'Other')], default='other', max_length=20)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_records', to='feed.post')),
                ('sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_shares', to='profiles.profile')),
            ],
            options={
                'db_table': 'feed_post_share',
                'indexes': [models.Index(fields=['post', '-created_at'], name='feed_post_s_post_id_526504_idx'), models.Index(fields=['code'], name='feed_post_s_code_fd319b_idx')],
                'constraints': [models.UniqueConstraint(fields=('post', 'sharer'), name='unique_post_sharer')],
            },
        ),
    ]
