# Generated by Django 5.2.17 on 2026-09-14 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0018_postshare'),
        ('profiles', '0009_recommendationfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_by', to='feed.post')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_posts', to='profiles.profile')),
            ],
            options={
                'db_table': 'feed_hidden_post',
                'indexes': [models.Index(fields=['viewer', '-created_at'], name='feed_hidden_viewer__2a1e8a_idx'), models.Index(fields=['post'], name='feed_hidden_post_id_7f4845_idx')],
                'unique_together': {('viewer', 'post')},
            },
        ),
        migrations.CreateModel(
            name='MutedAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('muted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_by', to='profiles.profile')),
                ('muter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors_muted', to='profiles.profile')),
            ],
            options={
                'db_table': 'feed_muted_author',
                'indexes': [models.Index(fields=['muter', '-created_at'], name='feed_muted__muter_i_0430c7_idx'), models.Index(fields=['muted'], name='feed_muted__muted_i_7aa2f2_idx')],
                'unique_together': {('muter', 'muted')},
            },
        ),
    ]
