# Generated by Django 5.2.17 on 2026-09-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0019_hiddenpost_mutedauthor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='meal_data',
        ),
        migrations.RemoveField(
            model_name='draft',
            name='progress_data',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meal_data',
        ),
        migrations.RemoveField(
            model_name='post',
            name='progress_data',
        ),
        migrations.AlterField(
            model_name='draft',
            name='post_type',
            field=models.CharField(choices=[('text', 'Text'), ('photo', 'Photo'), ('short_video', 'Short Video (BuddyClip)'), ('long_video', 'Long Video (BuddySession)'), ('workout_log', 'Workout Log'), ('moment', 'Moment (Story)'), ('poll', 'Poll')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('text', 'Text'), ('photo', 'Photo'), ('short_video', 'Short Video (BuddyClip)'), ('long_video', 'Long Video (BuddySession)'), ('workout_log', 'Workout Log'), ('moment', 'Moment (Story)'), ('poll', 'Poll')], max_length=20),
        ),
    ]
