# Generated by Django 5.2.17 on 2026-09-29 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0020_remove_draft_meal_data_remove_draft_progress_data_and_more'),
        ('profiles', '0009_recommendationfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=1)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_views', to='feed.post')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_views', to='profiles.profile')),
            ],
            options={
                'db_table': 'feed_post_view',
                'indexes': [models.Index(fields=['post', '-created_at'], name='feed_post_v_post_id_7ecd8b_idx'), models.Index(fields=['viewer', '-created_at'], name='feed_post_v_viewer__3bf18b_idx')],
                'unique_together': {('post', 'viewer')},
            },
        ),
    ]
